### ISSUE TITLE
problem with addAqueousPhaseWithElements('H O Na Cl C')

### ISSUE THREAD

**Issue by amandalemette** [reaktoro/reaktoro#100]
Hi, I'm new into python and I'm having an issue in using the attribute "addAqueousPhaseWithElements('H O Na Cl C')". I'm receiving the following error message:
AttributeError: 'reaktoro.PyReaktoro.ChemicalEditor' object has no attribute 'addAqueousPhaseWithElements'

So, I wrote the code: dir(editor) and the attribute 'addAqueousPhaseWithElements' is not in editor:

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'addAqueousPhase',
 'addGaseousPhase',
 'addMineralPhase',
 'addMineralReaction',
 'addPhase',
 'addReaction',
 'aqueousPhase',
 'createChemicalSystem',
 'createReactionSystem',
 'gaseousPhase',
 'mineralPhases',
 'setPressures',
 'setTemperatures']

How can I fix this?

**Comment by tadeu** [comment]
Hi @amandalemette, it looks like you are in an older version of Reaktoro. Do you know what version do you have? How did you install Reaktoro?

**Comment by amandalemette** [comment]
Hi @tadeu, How can I check the version I installed? I did the installation using anaconda through the command window.

**Comment by allanleal** [comment]
Hi @amandalemette . It's great you've used conda for installation. In this case, you can do the following (in a terminal):

~~~
conda list -n environment-name | grep reaktoro
~~~

In my machine, I have reaktoro installed in a conda *environment-name* named `rkt`, so I run:

~~~
conda list -n rkt | grep reaktoro
~~~

which I get:

~~~
reaktoro                  1.0.4            py37hc8805e9_0    conda-forge
~~~

To update it, you can do (assuming `rkt` as your environment name):

~~~
conda activate rkt
conda update reaktoro
~~~

It may be that your environment name is `base`. In this case, you may only need to do:

~~~
conda update reaktoro
~~~

Please let us know if this resolves your issue.

**Comment by amandalemette** [comment]
Thank you so much, it worked!!

**Comment by allanleal** [comment]
Great. Let us know if you need further assistance.
