### ISSUE TITLE
Installing Reaktoro using Conda in python 3.6

### ISSUE THREAD

**Issue by Jagirhussan** [reaktoro/reaktoro#110]
I would like to install reaktoro using conda. Currently, a binary distribution is provided in anaconda cloud at https://anaconda.org/conda-forge/reaktoro. This is built for python 3.7.
Installing this on a python 3.6 base automatically upgrades the python base to 3.7. 
An unfortunate side effect is that some applications are tied to python 3.6 and can no longer be used. For instance, the current distribution of FEniCS that could be installed via conda requires python 3.6.
It would be great if you could release a reaktoro distribution that works on python 3.6.

**Comment by allanleal** [comment]
Thanks @Jagirhussan , for reporting this issue. 

@tadeu Can we distribute both, 3.6 and 3.7? What about just Python 3.6, so that maybe Python 3.7 users can also use the 3.6 package (backward compatibility).

**Comment by allanleal** [comment]
Hi @Jagirhussan . So, here is something I just tried and it worked without any issues:

~~~bash
conda create -n fenics-reaktoro
conda activate fenics-reaktoro
conda install fenics reaktoro -y
python
>>> import reaktoro
>>> import fenics
~~~

Could you please create a clean environement (like above, e.g.,  `fenics-reaktoro`) and install `fenics` and `reaktoro` in it? 

You might also want to ensure conda is up to date before proceeding: `conda update -n base`

**Comment by Jagirhussan** [comment]
Hi Allan,
    Thanks for that. I was able to create the virtual environment and install both the packages. However, I had to use the conda-forge channel (may be the main one’s index was not updated yesterday). Also, it looks like the code changes from your pull request were not incorporated in the build. I get the error due to zero denominator (or phase with no species), error message below. This doesn’t affect me as I am working from the source.

Thanks and Regards
Jagir


Time:  0.0 (0.00%)
Traceback (most recent call last):
  File "transportUsingFEniCS.py", line 150, in <module>
    transport.step(field, dt)
  File "/ FEniCS/FEniCSDemo/transport/chemicaltransport.py", line 356, in step
    self.initialize(field)
  File "//FEniCS/FEniCSDemo/transport/chemicaltransport.py", line 184, in initialize
    for (state, boundary) in self.boundary_conditions]
  File "//FEniCS/FEniCSDemo/transport/chemicaltransport.py", line 184, in <listcomp>
    for (state, boundary) in self.boundary_conditions]
  File "/ FEniCS/FEniCSDemo/transport/chemicaltransport.py", line 12, in __init__
    self.fluid = mobility.fluid(state)
  File "/ FEniCS/FEniCSDemo/core/mobility.py", line 51, in fluid
    res.scaleVolume(1.0)
RuntimeError:
***********************************************************************
*** Error: Cannot scale the molar amounts of the species.
*** Reason: The given scalar is negative.
*** Location:  This error was encountered in Reaktoro/Core/ChemicalState.cpp:199.
***********************************************************************

**Comment by allanleal** [comment]
Hi Jagir. We have not yet made a new release in GitHub. I'll prepare one.
Once this is done, conda-forge will automatically update the package. Can
we close this issue then, or you think there is still something missing?

>
