### ISSUE TITLE
Create a PhaseArgs and use Struct designated initializers

### ISSUE THREAD

**Issue by alexandrebbruno** [reaktoro/reaktoro#113]
A discussion about the initialization and declaration of Phase surged during #94.  
Sugestion and discution: https://github.com/reaktoro/reaktoro/pull/94/files#r316507461

**Comment by allanleal** [comment]
Thanks, Alexandre, for opening this proposal. Defining phases and chemical system is now a bit different in Reaktoro v2, as shown in this tutorial [Defining Chemical Systems](https://reaktoro.org/tutorials/basics/defining-chemical-systems.html). Here is an example from this page:

![image](https://user-images.githubusercontent.com/5825588/152542641-01617095-b260-4a9a-b1ee-cea4dc55448f.png)
