### ISSUE TITLE
Use CoolProp for water?

### ISSUE THREAD

**Issue by ibell** [reaktoro/reaktoro#118]
I currently work at NIST and I had a discussion with a USGS guy in Boulder not so long ago, and my recollection was that PHREEQC didn't use the IAPWS-95 reference EOS, whereas it wouldn't be too tricky to do so, and CoolProp includes the IAPWS-95 reference EOS.  Just FYI.

**Comment by allanleal** [comment]
I think we should definitely use CoolProp as much as possible in Reaktoro (and now that you are concerned (or maybe always was) about computing these properties with automatic differentiation, this is another convincing point). 

Reaktoro implements two equations of state for water [HGK](https://github.com/reaktoro/reaktoro/blob/master/Reaktoro/Thermodynamics/Water/WaterHelmholtzStateHGK.cpp) and [Wagner and Pruss IAPWS 1995](https://github.com/reaktoro/reaktoro/blob/master/Reaktoro/Thermodynamics/Water/WaterHelmholtzStateWagnerPruss.cpp). 

The dependency on PHREEQC is optional; for users that want to use its thermodynamic databases and activity models, while relying on Reaktoro's algorithm for chemical equilibrium calculation, for example. I call this a PHREEQC backend, but again, only used if one wants to replicate PHREEQC geochemical modeling results when using Reaktoro.

Note the use of `ThermoScalar` type. This is the original automatic diff type that I have been using for quite some years now, but the plan is to change this to `autodiff::dual` (or most likely `autodiff::real`).

Reaktoro also has other AD types (specific for thermochemical prop calculation). `ChemicalScalar` for example, which computes derivatives with respect to *T*, *P*, and **n**, where **n** is a vector of species amounts. `ThermoScalar` is for properties that depend only on *T* and *P*.

Nowadays I don't like this anymore. I want to replace all these types (and also `ThermoVector` and `ChemicalVector`) by `autodiff::real` and `autodiff::VectorXr`). This is not a trivial task though, unfortunately.

I wonder what else CoolProp capabilities you suggest that could be useful for this project? Do you also compute activities/fugacities of non-ideal fluid/solid phases (and other excess related properties)? I need always to be able to compute derivatives of these properties w.r.t. *T*, *P*, and **n** (or **x**, where **x** is a vector of mole fractions).

**Comment by ibell** [comment]
The IAPWS-95 is the one I was thinking of for water (default water EOS in CoolProp).

CoolProp has the ability to calculate analytic values for derivatives of properties of mixtures in the fluid phase w.r.t. T,p,x, but not all combinations are supported, unfortunately, and almost none are exposed to the outside world given the absurd number of possible combinations and the struggle of coming up with a vaguely sane API as a result.  All combinations are implemented for pure fluids, though.

**Comment by allanleal** [comment]
I know the issue you are talking about. I'll close this issue (and be in touch for possible cooperation in this regard).
