### ISSUE TITLE
Create conda package using conda-forge

### ISSUE THREAD

**Issue by tadeu** [reaktoro/reaktoro#12]
This issue is just to track the effort on creating a conda package on conda-forge. I'm trying to add a recipe here: https://github.com/conda-forge/staged-recipes/pull/6799

**Comment by tadeu** [comment]
It seems that there's still no support for adding a new recipe already using the new compilers:

> @tadeu That won't work both because of staged-recipes and also because that command doesn't do that. :) I don't think it's possible to use the new compilers in staged-recipes at this point. Many of the dependencies for most packages also still aren't migrated to be usable yet, e.g. numpy....

https://gitter.im/conda-forge/conda-forge.github.io?at=5bbcadb6435c2a518e77fadc

The current conda-forge infrastructure still uses GCC 4.8.2 (there is an ongoing effort to migrate to GCC 7.3), and it seems that Reaktoro doesn't support a compiler that old:

```
thirdparty/install/include/nlohmann/json.hpp:127:10: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
         #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
          ^
```
(from the build [here](https://circleci.com/gh/conda-forge/staged-recipes/30927))

**Comment by allanleal** [comment]
Are we prevented from using conda-forge because of this? I'm considering using C++17 for some new libs, and this will restrict even more later the compiler version.

**Comment by tadeu** [comment]
Yes, for now we are prevented from using conda-forge, but soon we'll be able to build it with the new compilers. It's ok to use C++17 , GCC 7 already supports it :)

**Comment by nicoddemus** [comment]
I think we can close this @tadeu?
