### ISSUE TITLE
PyReaktoro with pip

### ISSUE THREAD

**Issue by volpatto** [reaktoro/reaktoro#126]
Hi, @allanleal and contributors!

This issue is a proposal. What do you all think about put `reaktoro`'s Python bindings inside `pip`? I know that it can be challenging, since `reaktoro` has external dependencies that aren't available in PyPI.

In this regard, I found [conda-press](https://github.com/regro/conda-press), which looks promising. Would it be possible to generate `reaktoro`'s wheels from there? If yes, then would it be possible to put it into PyPI?

Thanks and congratulations for the nice work here!

**Comment by allanleal** [comment]
I think this is a very good idea for those that may not want to use conda, and may have other python environment technologies in use (instead of conda env). I can't assess the feasibility of this, though. @tadeu and @nicoddemus are the right guys here to comment about this! :)

**Comment by tadeu** [comment]
I have read good things about [conda-press](https://github.com/regro/conda-press) and it surely looks very promising (or very good already), but I haven't used it yet and I don't know how much effort would it be. If there are already some packages being published as wheels on PyPI using `conda-press`, that could be used as a starting point.

**Comment by volpatto** [comment]
I tried to find something generated by `conda-press`, but I failed. I tried myself to generate, but no success at all. Maybe a help from the maintainers could give us some light.

**Comment by sabualkaz** [comment]
Hi @allanleal. Just wondering if there is any progress on this. I would love to use reaktoro for work but we have a strict pip only policy.

**Comment by allanleal** [comment]
Hi @sabualkaz , nothing much has happened for enabling `pip install` for installing Reaktoro. @volpatto was working on it in the past.

I understand using `conda` instead of `pip` may not be a solution to all users. I would like to hear from you why `conda` is not adequate for you.

**Comment by volpatto** [comment]
We have no progress at all, @sabualkaz. Sorry. However, it doesn't look like a difficult task, we have to build the Python wheels for `PyReaktoro` then publish it. I am willing to return to this task as soon as I have some time.

**Comment by sabualkaz** [comment]
@allanleal thanks for the update. The main reason is that there are more packages that we use on `pip` and not on `conda` than the other way round. Managing packages with both `pip` and `conda` has caused issues in the past. 

@volpatto thanks for picking this up. No rush as I have started exploring `phreeqcpython` on pip for now. However, I find the structure of `reaktoro` much more intuitive and clearer which why I prefer to use it in the future. I am mainly doing equilibrium calculations for now but intending to explore more transport phenomena.

**Comment by volpatto** [comment]
Working on it in #187

**Comment by volpatto** [comment]
Addressed in #193. Closing the issue.

**Comment by allanleal** [comment]
Great - awesome work, Diego!
