### ISSUE TITLE
Solid-gas-aqueous speciation 

### ISSUE THREAD

**Issue by EnriqueGarciaFranco** [reaktoro/reaktoro#129]
Dear developers:

I have happened to find your interesting Python library on the internet.

I would like to perform **solid-gas-aqueous speciation** of a solution of NaCl, 

_given an amount of NaCl (s), an amount of a given aqueous KCl-bearing solution and some selected T,P._

 Would Reaktoro support this option?

I am trying to mimic the Uranium example attached to the **PHREEQC** database thread (on reaktoro.org).

Unfortunately, I have been unsuccessful.

May I humbly ask you to help me out with the syntax?

Thanks in advance for your valuable time.

**Comment by allanleal** [comment]
Hi Enrique. Let's discuss this on the Gitter channel https://gitter.im/reaktoro/community

I'm on vacation but we'll try to help. Please give more details there on what is the problem you want to solve.
