### ISSUE TITLE
Compiling reaktoro-app using CMake

### ISSUE THREAD

**Issue by roliveira** [reaktoro/reaktoro#130]
I've unsuccessfully been trying to build the `reaktoro-app` inside the `/demos/cmake/reaktoro-app/` folder. I've simply followed the instrucitons in the `README.rst` file but it complains about a missing `ThermoFun::ThermoFun` target. It does warn about it in the config step:

```
-- Configuring done
CMake Error at CMakeLists.txt:17 (add_executable):
  Target "app" links to target "ThermoFun::ThermoFun" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

... but I went ahead and tried to build it anyways and it crashes linking it:

```
Scanning dependencies of target app
[ 50%] Building CXX object CMakeFiles/app.dir/main.cpp.o
[100%] Linking CXX executable app
/usr/bin/ld: cannot find -lThermoFun::ThermoFun
collect2: error: ld returned 1 exit status
CMakeFiles/app.dir/build.make:84: recipe for target 'app' failed
make[2]: *** [app] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/app.dir/all' failed
make[1]: *** [CMakeFiles/app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Adding `find_package(ThermoFun REQUIRED)` to the `CMakeFiles.txt` fixes this but I'm not sure if this was an intended behavior. 

Cheers!

**Comment by roliveira** [comment]
I've added the pull request with a little patch to fix this in case the ThermoFun package is indeed required to build the cmake app.

**Comment by allanleal** [comment]
This was indeed a bug. Thanks for fixing it with PR #131 .
