### ISSUE TITLE
New conftest needs to be moved to tests dir

### ISSUE THREAD

**Issue by allanleal** [reaktoro/reaktoro#144]
There is a new `conftest.py` file after merging PR #141 under `reaktoro/Reaktoro`, but this should be moved to `reaktoro/tests` (perhaps merged with the existing one `reaktoro/tests/conftest.py`). 

There is also regression data being stored under the C++ source dir:

~~~
reaktoro/Reaktoro/Core/ChemicalState-test/test_chemical_state_output_with_gaseous_phase_only.txt
~~~

which should be stored in `reaktoro/tests/regression`.

**Comment by volpatto** [comment]
Solved in #146, so I'm closing this issue.
