### ISSUE TITLE
Error during the source compilation

### ISSUE THREAD

**Issue by jontateixeira** [reaktoro/reaktoro#147]
Hi, Allan and contributors!!!!

I am trying to compile Reaktoro from the source, but during the final process (after the pybind11 and Thermofun were compiled), the following error message is printed:
```
john@john-DELL ~/workspace/pro/src/reaktoro/reaktoro_src $ cmake ../reaktoro -DCMAKE_INSTALL_PREFIX=~/opt/reaktoro -DBUILD_PYTHON=ON -DBUILD_DEMOS=ON
-- Boost version: 1.67.0
CMake Error at cmake/ReaktoroFindDeps.cmake:8 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".
Call Stack (most recent call first):
  CMakeLists.txt:83 (include)
```

However, when I type this: 
`grep -r -n "add_compile_definitions"` 

I find this: 
`cmake/ReaktoroFindDeps.cmake:8:    add_compile_definitions(REAKTORO_USING_THERMOFUN)
`

Thank you in advance for the help.

Jonathan

**Comment by volpatto** [comment]
Hi, @jontateixeira!

Thanks for your interest in `Reaktoro`.

This error sounds untypical. Could you please say step by step what you did in order to compile Reaktoro?

I'd recommend to use `conda` with `conda devenv` to manage everything you need in order to compile and build Reaktoro. It looks like that you are not running CMake inside a `conda` environment, and things can get a little harder this way.

Cheers!

**Comment by jontateixeira** [comment]
Hi Diego, 

Thank you for your response and advice!!!

I was using a script that I created in the last year... the only step that I added, **today**, it was the building of ThermoFun (That I believe to be a new dependence of Reaktoro)... Anyway, I think it's the fact that I'm not using the `conda devenv`, and I'll try to do my best and then I will give a feedback!!! 

 -------------------------------------------------------------
the step-by-step that "I did" (the script and then myself -> biuld the ThermoFun), to compile the Reaktor is the following:

 Adding some specific repos...
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test && sudo apt update
sudo add-apt-repository ppa:fenics-packages/fenics && sudo apt-get update
```
 installing pre-req
```
sudo apt install software-properties-common g++-7 gnuplot gnuplot-qt python3-pip python3-dev curl autoconf automake bash-completion bison libopenmpi-dev python3-dev python3-h5py python3-numpy python3-ply python3-six python3-urllib3 python3-scipy python3-mpi4py screen wget xauth xterm git git-flow checkinstall zlib1g libreadline-dev python3-sympy openmpi-bin rsync libssl-dev flex gfortran gfortran-7 hwloc-nox libblas-dev libboost-dev libboost1.65-dev libcr-dev libcr0 libfl-dev libfl2 libgfortran-7-dev liblapack-dev libmpich-dev libmpich12  mercurial mercurial-common mpich python3-venv python3.6-venv zlib1g-dev
```

Other little upgrades... 
```
sudo pip3 install --upgrade pip && sudo pip3 install pyinstaller tabulate
sudo pip3 install meshio && sudo pip3 install -U pylint --user
cd $HOME/bld && git clone https://github.com/pybind/pybind11.git && cd pybind11 && mkdir build
cd build && cmake .. && make check -j 4 && 
checkinstall --pkgname=pybind11 --pkgversion="_:$(date +%Y%m%d%H%M)" --backup=no --deldoc=yes --fstrans=no --default  
mv -vf *.deb $HOME/pkgs_installed/
```

Compilling boost.python 1.67.0 :: Previously downloaded
```
cd $HOME/bld/boost_1_67_0/
./bootstrap.sh --with-python=python3.5
echo "using mpi ;" >> project-config.jam
sudo ./bjam -j3  --layout=tagged variant=release threading=multi link=shared
sudo checkinstall --pkgname=boost_1_67_0 --pkgversion="_:$(date +%Y%m%d%H%M)" --backup=no --deldoc=yes --fstrans=no --default  
sudo mv -vf *.deb $HOME/pkgs_installed/
```

installing firedrake
```
cd $HOME/opt/ && curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
python3 firedrake-install --slepc --verbose --disable-ssh
echo "source $MYOPT/firedrake/bin/activate" > $HOME/opt/aliases/active_firedrake
source $MYOPT/firedrake/bin/activate
```

ThermoFun dependence (this part I done today ok?)
```
cd $HOME/bld
git clone https://github.com/thermohub/thermofun.git && cd thermofun 
sudo ./install-dependencies.sh
mkdir build && cd build && cmake ../ && make
checkinstall --pkgname=thermofun --pkgversion="_:$(date +%Y%m%d%H%M)" --backup=no --deldoc=yes --fstrans=no --default
mv -vf *.deb $HOME/pkgs_installed/
```

And finally... installing Reaktoro
```
cd $WKSRC/reaktoro/reaktoro/    
git co master
mkdir -p ../reaktoro_src && cd reaktoro_src/
cmake ../reaktoro -DCMAKE_INSTALL_PREFIX=~/opt/reaktoro -DBUILD_PYTHON=ON -DBUILD_DEMOS=ON 
```

**Comment by jontateixeira** [comment]
Hi Diego, me again...

Man! you are right! using `conda devenv` was what was missing! Very good job! 

Tks Man!!

**Comment by volpatto** [comment]
> Hi Diego, me again...
> 
> Man! you are right! using `conda devenv` was what was missing! Very good job!
> 
> Tks Man!!

Hi, @jontateixeira!

Great!! `conda devenv` does the work for us! If you hit more problems, please always feel free to contact us.

Enjoy! :)

P.S.: BTW, I can tell that Reaktoro + Firedrake is a very good combination (personal experiences). However, if I could give you some advice, I would like to recommend you double attention while installing Firedrake inside a `conda` environment. Since Firedrake has its own installation script in a PETSc fashion, it can present some difficulties related to `conda` envs symlinks.

**Comment by allanleal** [comment]
Hi @jontateixeira - @volpatto's suggestion of using `conda` for managing Reaktoro dependencies is the best solution to get this right. Let us know if you have further issues. We have also coupled Reaktoro and Firedrake and the result was very good.
