### ISSUE TITLE
Change repository name from Reaktoro to reaktoro

### ISSUE THREAD

**Issue by allanleal** [reaktoro/reaktoro#15]
Guys, about two years ago, this Reaktoro repository was created for some experimental work on CI and for some reason it remained named in title case Reaktoro.

However, in BitBucket it was always named reaktoro, which results in a nicer URL in my opinion:

`github.com/reaktoro/reaktoro`

This is a proposal to name this and other repositories in this organization with lower case letters.

**Comment by nicoddemus** [comment]
I'm 👍 on it. If we all agree, it is just a matter of renaming the repository here on GitHub and update scripts, if any. GitHub will also automatically redirect the old url to the new one, so that's nice.

**Comment by alexandrebbruno** [comment]
Fine by me, agree 👍

**Comment by nicoddemus** [comment]
Done. 😁
