### ISSUE TITLE
Very slow ChemicalSystem initialization when using ThermoFun database

### ISSUE THREAD

**Issue by martinvoigt** [reaktoro/reaktoro#150]
It seems that initializing a `ChemicalSystem` takes quite a while (a minute or so on my computer, even for a simple system with only H, O, Na, Cl, C), when using a `ThermoFun` database and not a reaktoro-native one.

Example:
```python
import thermofun as tf
from reaktoro import *

db = tf.Database('aq17-thermofun.json') # requires having this database file present

editor = ChemicalEditor(db)
editor.addAqueousPhaseWithElements('H O Na Cl C')
editor.addGaseousPhase(['CO2(g)'])

system = ChemicalSystem(editor) # this takes quite long


db = Database('supcrt98.xml')

editor = ChemicalEditor(db)
editor.addAqueousPhaseWithElements('H O Na Cl C')
editor.addGaseousPhase(['CO2(g)'])

system = ChemicalSystem(editor) # nice and fast
```

I hope that this can/will be improved?

**Comment by allanleal** [comment]
It's indeed taking more time than it should. It gets worse as more elements are added (causing more species to be considered in the system). This is most likely something to do with the construction of interpolation tables during the `ChemicalSystem` initialization. I'll debug here and see what is going on.

**Comment by allanleal** [comment]
A fix is now on the way @martinvoigt . I'll produce a new conda release soon, once CI finishes. I'll keep this open until you try out from your side and check if the issue is gone.

**Comment by allanleal** [comment]
Hi @martinvoigt . There is now a new version (v1.1.1) in conda that should fix this issue (it fixed in my machine). Please do:

~~~text
conda activate myenv
conda update reaktoro
~~~

and see if the issue is resolved. `myenv` is the conda environment where you installed `reaktoro` (maybe `base`).

**Comment by martinvoigt** [comment]
@allanleal Many thanks - I tried it and it's much faster now! Still slightly slower compared to using a native database, when creating a `ChemicalState` from an editor for the first time, but not a noticeable issue for me!
