### ISSUE TITLE
CommandNotFoundError: No command 'conda devenv'. Did you mean 'conda env'?

### ISSUE THREAD

**Issue by thsorcerer** [reaktoro/reaktoro#153]
hello,
I'm trying to create an environment for reaktoro using 'conda devenv' but, it doesn't recognize the command devenv. Do you know how can this be addressed?

<img width="749" alt="Screenshot 2020-05-18 at 14 30 07" src="https://user-images.githubusercontent.com/65565848/82252359-7d5f1380-9914-11ea-8f0c-65bb2fb65f35.png">

**Comment by allanleal** [comment]
Hi @thsorcerer . You only need `conda-devenv` tool if you are going to develop Reaktoro. What you may want instead is indeed the `conda env create` command to create an environment:

~~~
conda env create -n myenvname reaktoro
~~~

This will create an environment named `myenvname` in which `reaktoro` is installed. You can activate this env with:

~~~
conda activate myenvname
~~~

Let me know if this helps.

**Comment by thsorcerer** [comment]
> Hi @thsorcerer . You only need `conda-devenv` tool if you are going to develop Reaktoro. What you may want instead is indeed the `conda env create` command to create an environment:
> 
> ```
> conda env create -n myenvname reaktoro
> ```
> 
> This will create an environment named `myenvname` in which `reaktoro` is installed. You can activate this env with:
> 
> ```
> conda activate myenvname
> ```
> 
> Let me know if this helps.

Hey @allanleal! 
It actually works just perfect, thank you very much!

Cheers

**Comment by allanleal** [comment]
Great, thanks for letting me know!
