### ISSUE TITLE
Conflicts with nlohmann/json.hpp

### ISSUE THREAD

**Issue by roliveira** [reaktoro/reaktoro#154]
It seems like there is a conflict when including `Reaktoro.hpp` and `nlohmann/json.hpp`. I can easily overcome it by ignoring nlohmann's lib and using the one within Reaktoro, but given that there is a Reaktoro namesapce, is this supposed to happen?

**Comment by volpatto** [comment]
Hi, @roliveira!

@allanleal is on holiday right now. I'll try to figure out what is happening ASAP.

Cheers!

**Comment by tadeu** [comment]
Probably the `nlohmann_json` version that is [inside Reaktoro repository](https://github.com/reaktoro/reaktoro/blob/master/Reaktoro/deps/json/json.hpp) is not up-to-date. Since there's a [conda-forge package](https://github.com/conda-forge/nlohmann_json-feedstock) for `nlohmann_json`, perhaps this header can be removed from Reaktoro's repo, and be used as a conda dependency?

**Comment by volpatto** [comment]
> Probably the `nlohmann_json` version that is [inside Reaktoro repository](https://github.com/reaktoro/reaktoro/blob/master/Reaktoro/deps/json/json.hpp) is not up-to-date. Since there's a [conda-forge package](https://github.com/conda-forge/nlohmann_json-feedstock) for `nlohmann_json`, perhaps this header can be removed from Reaktoro's repo, and `nlohmann_json` be used as a conda dependency?

Good idea! I was planning to check exactly `nlohmann_json` compatibility with `reaktoro`'s JSON usage. Leaving all dependency issues to `conda` is always a good plan, I think.

**Comment by volpatto** [comment]
@roliveira could you please tell us what version of `nlohmann_json` you have tried to use and in which operational system? Thanks!

**Comment by roliveira** [comment]
I'm in Ubuntu 18.04 (WSL) and I'm using the latest version of `nlohmann_json` available in the git repository being pulled and populated using CMake's `ExternalProject_Add`. 

I noticed in #155 that the error comes in Windows and a particular version of the lib. So I'll work on a MWE later this week to reproduce this error making sure I'm not messing up any creating any linking problems with`Reaktoro` instead.

Later this week I can work on a MWE to test it out. 

Thanks!

**Comment by volpatto** [comment]
> I'm in Ubuntu 18.04 (WSL) and I'm using the latest version of `nlohmann_json` available in the git repository being pulled and populated using CMake's `ExternalProject_Add`.
> 
> I noticed in #155 that the error comes in Windows and a particular version of the lib. So I'll work on a MWE later this week to reproduce this error making sure I'm not messing up any creating any linking problems with`Reaktoro` instead.
> 
> Later this week I can work on a MWE to test it out.
> 
> Thanks!

Great, @roliveira! In the meantime, I'll try to figure out if there is a way to avoid errors (in Reaktoro's side) with `nlohmann_json` recent releases.

**Comment by allanleal** [comment]
Hi @volpatto @roliveira - can we close this issue? I thought it was resolved in #155 .

**Comment by roliveira** [comment]
Yes - resolved in #155

**Comment by allanleal** [comment]
Hi @roliveira , thanks - please contact me via gitter gitter.im/allanleal
