### ISSUE TITLE
Change to a more robust Windows CI alternative.

### ISSUE THREAD

**Issue by volpatto** [reaktoro/reaktoro#156]
Hi, Reaktoro folks!

I'm opening this issue to make a proposal. What do you guys think about changing the Win CI (currently AppVeyor) to another CI? For instance, Github Actions?

AppVeyor showed some issues so far. For example, have a look at these: #155 and #154 and comments therein. Moreover, Github Actions is a GitHub tool, better support and etc, plus very quick builds. We could, of course, move from Travis to GH Actions for Linux too.

Please share your thoughts about it.

**Comment by allanleal** [comment]
I would say we could use GitHub Actions for all OSs, like you implemented for `autodiff`.

**Comment by volpatto** [comment]
Great, then! I'll do it when I manage to find some time.

**Comment by allanleal** [comment]
Hi Diego, since Azure Pipelines have been used in Reaktoro for quite some time already (instead of AppVeyor), I think this issue/proposal can be closed.
