### ISSUE TITLE
Investigate the Flaky in Phreeqc output format

### ISSUE THREAD

**Issue by OtavioPellicano** [reaktoro/reaktoro#162]
Sometimes when I run `Phreeqc::execute()` method, the output change a little (see the image below). I noticed that change is always in `Solution composition`.

Code example:
```
    std::string database_path = "W:/reaktoro_processing/DATABASE/phreeqc.dat";
    std::string input_path = "W:/reaktoro_processing/IN/IW.pqi";
    std::string output_path = "W:/reaktoro_processing/OUT/IW.pqo";
    
    Phreeqc phreeqc(database_path);
    phreeqc.execute(input_path, output_path);
```

IW.pqo fragment:

![image](https://user-images.githubusercontent.com/27929707/96025487-91f3f900-0e2b-11eb-995d-cd397afaf47c.png)

**Comment by OtavioPellicano** [comment]
I believe I found the error! If your input files are encoded as ANSI, instead of UTF-8, sometimes that line appears. One thing strange is that even with all inputs as UTF-8, the output will be encoded as ANSI.

**Comment by allanleal** [comment]
OK, great - I'll close this issue then. I think any fix for such behavior would be better addressed directly in PHREEQC, and not in Reaktoro.
