### ISSUE TITLE
Non-aqueous electrolyte class

### ISSUE THREAD

**Issue by MayaStr** [reaktoro/reaktoro#163]
Hello everyone,

I would like to simulate a non-aqueous electrolyte solution for battery chemistry. As far as I understand, this is not possible with the current phases aqueous and liquid. The class would be a generalized version of Aqueous with possibility to specify the solvent.

Do you think this can be added to Reaktoro? I would like to try to implement it, but I would surely need some help.

Maya

**Comment by allanleal** [comment]
I'm currently developing Reaktoro v2.0 (the next version) in which the library is almost completely redesigned. One of the reasons for this is to make it easier to extend Reaktoro to support new phase/species/reaction types.

The current version can still be extended to new phase types (just follow what has been done for the existing `AqueousPhase`, `GaseousPhase`, `MineralPhase` classes). The best approach, however, would be to coordinate and discuss this further to implement in v2.0. There is still no release for this version, but I intend to make preliminary releases within the next months.

In Reaktoro v2.0, you define a new custom phase by creating an object of class `Phase`, populate it with `Species` objects, and attach an activity model for it. BTW, what kind of activity model are you considering for this non-aqueous electrolyte solution?
The `Species` object must also know how to compute its standard thermodynamic properties (by either setting a `StandardThermoModel` that computes *G0(T, P)*, *H0(T, P)*, etc., or a `FormationReaction` that computes reaction logK and delta(H) at *T,P*). 

This still needs to be properly documented, but I hope it gives you an idea of the upcoming possibilities in Reaktoro v2.0 in terms of easy-to-extend capability.

**Comment by MayaStr** [comment]
Thanks for your quick response!
The chemistry of battery electrolytes has not been studied as much as aqueous solutions. As far as I know there is no database containing the necessary values. As a first experiment I will try a Debye Hückel model I found in literature. 
Please let me know how I can help to implement it in v2.0.

**Comment by allanleal** [comment]
> As far as I know there is no database containing the necessary values.

In this case, how are you planning to compute thermodynamic properties? For chemical equilibrium calculations of such complex solutions, we need to either have thermodynamic data in the form of standard Gibbs energies or log(K) of reactions.

**Comment by allanleal** [comment]
Hi Maya, I'll close this issue/discussion for now. Please reopen if you are still interested in this development and if some sort of collaboration can be established to get this functionally implemented in the new version of Reaktoro, v2. 

Please check the new website (still under construction) to learn more: https://reaktoro.org.
