### ISSUE TITLE
Default equilibrium algorithm and how to remove species

### ISSUE THREAD

**Issue by avlmachado** [reaktoro/reaktoro#171]
First of all, I would like to thank the developers of Reaktoro. I had the experience of coding a geochemical problem before and I know how it can be undoubtedly unstable. On the other hand, Reaktoro seems to be the opposite according to some tests I have made. Thus, I have been considering the best option for my problem of coupling a geochemical code with a reactive transport code.

However, I have some questions. The first is more to understand the code and properly cite which of the published papers represents the present state. For example, when I just invoke a kinetic or equilibrium problem, for the current state in the master branch, Reaktoro is using for equilibrium or partial equilibrium reactions, by default, the extend Law of mass action or Gibbs energy minimization algorithm?

My second question is regarding the possibility of removing species, is it possible?

For example, I have a problem where I put CO2 with brine, in equilibrium. In the next step, I want to remove the gaseous phase and let the state just be an aqueous phase, because I am going to use this state to set a single-phase problem of carbonated water injection. 

Sds,

Alex Machado

**Comment by allanleal** [comment]
Hi Alex. Thanks for your words. The main algorithm in Reaktoro for chemical equilibrium calculations is based on Gibbs energy minimization using an interior point method. This is what you use by default (and it is the recommended algorithm). The details of the algorithm are presented in the following papers:

* Leal, A.M.M., Kulik, D.A., Kosakowski, G. (2016). Computational methods for reactive transport modeling: A Gibbs energy minimization approach for multiphase equilibrium calculations. Advances in Water Resources, 88, 231–240. https://doi.org/10.1016/j.advwatres.2015.11.021

* Leal, A.M.M., Kulik, D.A., Smith, W.R., Saar, M.O. (2017). An overview of computational methods for chemical equilibrium and kinetic calculations for geochemical and reactive transport modeling. Pure and Applied Chemistry, 89(5), 597–643. https://doi.org/10.1515/pac-2016-1107

Let me know if you cannot download these papers for free. 

You can use the following to cite Reaktoro at the moment (this may change, but the new form will be updated on the website):

*Leal, A.M.M. (2015). Reaktoro: An open-source unified framework for modeling chemically reactive systems. www.reaktoro.org*

~~~
@misc{Leal2015,
author = {Leal, Allan M. M.},
title = {{Reaktoro: An open-source unified framework for modeling chemically reactive systems}},
url = {www.reaktoro.org},
year = {2015}
}
~~~

> My second question is regarding the possibility of removing species, is it possible?

You can actually construct the phases (e.g., the aqueous phase) with exactly the species you want:

~~~py
db = Database("supcrt98.xml")

editor = ChemicalEditor(db)
editor.addAqueousPhase(["H2O(l)", "H+", "OH-", "HCO3-", "CO2(aq)", "CO3--"])
~~~

> For example, I have a problem where I put CO2 with brine, in equilibrium. In the next step, I want to remove the gaseous phase and let the state just be an aqueous phase, because I am going to use this state to set a single-phase problem of carbonated water injection.

I'm not sure I understand what you mean by removing the gaseous phase. There are several possibilities. I think the easiest is to stick with a `ChemicalSystem` object containing all phases and species of interest (this includes the gaseous phase). You can set the amounts of the species in a phase to zero:

~~~py
state.scalePhaseVolume("Gaseous", 0.0)  # this will effectively set to zero the amounts of all gases
~~~

If you what you mean is ignoring certain species or phases in an equilibrium calculation, you can use the `Partition` class:

~~~py
db = Database("supcrt98.xml")

editor = ChemicalEditor(db)
editor.addAqueousPhase(["H2O(l)", "H+", "OH-", "Na+", "Cl-", "HCO3-", "CO2(aq)", "CO3--"])
editor.addGaseousPhase(["CO2(g)"])

system = ChemicalSystem(editor)

state = equilibrate(problem)
state.setTemperature(55.0, "celsius")
state.setPressure(90.0, "bar")
state.setSpeciesAmount("H2O(l)", 55.0, "mol")
state.setSpeciesAmount("Na+", 1.0, "mol")
state.setSpeciesAmount("Cl-", 1.0, "mol")
state.setSpeciesAmount("CO2(aq)", 1.0, "mol")
state.setSpeciesAmount("CO2(g)", 10.0, "mol")

partition = Partition(system)
partition.setInertPhases(["Gaseous"])

equilibrate(state, partition)  # state.speciesAmount("CO2(g)") should remain 10.0 mol

print( state.speciesAmount("CO2(g)") )  # this should print 10.0 - the initial amount of CO2(g) not touched by the equilibrium calculation
~~~
*I have not tested the code above! :)*

We can chat more on Gitter: https://gitter.im/reaktoro/community

**Comment by avlmachado** [comment]
Dear Allan, thank you very much for your answers.

Regarding the second question, I think the first option you mention is possible for my case.

The idea of equilibrating CO2 with water is only to know the CO2 content in the aqueous phase for a given pressure and temperature and using this state to set up a boundary condition of carbonated water injection into a porous medium (i.e. single-phase flow).

I'm coupling with another transport code, but the [reactive transport example in the tutorials](https://reaktoro.org/tutorials/transport/reactivetransportsolver-calcite-brine.html) is a good example to explain my idea.

In this tutorial, the CO2 in the aqueous phase is directly set by the user (currently I'm doing the same in my code, and calculating this value from another code):
```python
problem_bc.add('CO2', 0.75, 'mol')
```

But I'd like to set up the solubility according to the pressure and temperature.

**Comment by allanleal** [comment]
Yes, that tutorial showing the use of `ChemicalState::scalePhaseVolume` will help to achieve what you want. In that tutorial, we use it to control the volumes of the phases so that we start the reactive transport simulation with the desired porosity (10%) and mineral volume composition. 

I'll close this issue now. We can chat in Gitter for further details.
