### ISSUE TITLE
gems/node.h isn't found by the compiler

### ISSUE THREAD

**Issue by yurivict** [reaktoro/reaktoro#178]
Offending line: https://github.com/reaktoro/reaktoro/blob/master/Reaktoro/Interfaces/Gems.cpp#L28

Error:
```
/usr/ports/science/reaktoro/work/reaktoro-1.2.2/Reaktoro/Interfaces/Gems.cpp:28:10: fatal error: 'gems/node.h' file not found
#include <gems/node.h>
         ^~~~~~~~~~~~~
1 error generated.
```

clang-10
FreeBSD 12.2

**Comment by yurivict** [comment]
Same with headers in ```thirdparty/phreeqc/common```, ```thirdparty/phreeqc/PhreeqcKeywords```.

You need to add ```-I${dir}``` for them.

**Comment by allanleal** [comment]
What were your steps to get to this error?

**Comment by yurivict** [comment]
```cmake . && gmake```

**Comment by yurivict** [comment]
I was able to proceed by adding ```-I${WRKSRC}/thirdparty``` to ```CXXFLAGS``` but later got into another problem https://github.com/reaktoro/reaktoro/issues/179

**Comment by allanleal** [comment]
out of source build?

**Comment by yurivict** [comment]
> Out-of-source build?

Yes

> Another thing, are you using conda {...}

No

**Comment by allanleal** [comment]
Conda is not the issue here. I wonder if your `gmake` is what I use here as `make`.

**Comment by allanleal** [comment]
If you have ninja, try:

~~~
cmake -GNinja ..
ninja
~~~

**Comment by yurivict** [comment]
Same as make.

**Comment by allanleal** [comment]
I have `clang-11` here. Just tried with it as well, and the compilation succeeded (libReaktoro, python bindings, etc.).

**Comment by allanleal** [comment]
Closing this issue for the same reasons as those presented in #179. I don't think it's worth it, but I'll be happy to accept a PR to resolve this issue if someone thinks this is important.
