### ISSUE TITLE
Installed include/cvode/cvode.h conflicts with sundials that installs cvode

### ISSUE THREAD

**Issue by yurivict** [reaktoro/reaktoro#179]
Instead of bundling cvode you should depends on cvode from the sundials package.

Sundials packages are available on about every distro: https://repology.org/project/sundials/versions

**Comment by allanleal** [comment]
Yes, this superbuild approach in Reaktoro started a few started years ago before `conda` became its dependency manager. cvode is available in conda-forge, which is probably from where we'll pick it for our day-to-day development.

**Comment by yurivict** [comment]
I don't use conda. Package managers don't use conda.

**Comment by allanleal** [comment]
Conda is just to simplify dependency management. Not every library is available via package managers of operating systems.

You don't need to use conda if you are happy installing every dependency yourself. CMake `find_package` should pick up the libraries needed for you. 

At the moment, however, there is no `find_package(cvode)` in Reaktoro. We are bound to use the cvode library built together with Reaktoro.

**Comment by yurivict** [comment]
> You don't need to use conda if you are happy installing every dependency yourself.

I would like to create a package for ```reaktoro``` and conda is not an option for package managers. conda downloads files, and all downloads need to be fingerprinted for security reasons, this is why conda is not compatible with package managers.

You should support both conda and non-conda users.

It should be possible to individually choose libraries that are used as packages, or as bundled dependencies.

**Comment by allanleal** [comment]
Right. I'm open to alternatives. Let me know what you have in mind more specifically.

**Comment by yurivict** [comment]
Please add cmake options for dependencies, for example ```USE_EXTERNAL_CVODE```.

**Comment by allanleal** [comment]
Working on it. Just installed cvode v2.8.2 (I know, it's outdated) using:

~~~
mkdir build
cmake .. -DEXAMPLES_ENABLE=OFF -DEXAMPLES_INSTALL=OFF -DCMAKE_INSTALL_PREFIX=install
make -j
~~~

I'll now try to get `find_package(cvode)` to work and see if my changes can be committed.

**Comment by allanleal** [comment]
I've create a PR for this. You can also check out the branch:

https://github.com/allanleal/reaktoro/tree/add-cmake-options-to-prevent-deps-from-building-automatically

We'll soon have version 2.0 of Reaktoro. In this new version, there are some new deps (and some removed). 

We would need packages for:

* https://github.com/autodiff/autodiff
* https://github.com/reaktoro/optima

I've put `autodiff` on conda already. Optima not yet. Anyway, I don't know yet what you are going to do exactly (but I sense it is something similar to `apt-get install ` in Ubuntu?!). It would be great to have packages for these libs also.

**Comment by allanleal** [comment]
CVODE is no longer used in [Reaktoro v2](https:/reaktoro.org), which does not encapsulate dependencies like Reaktoro v1. In my opinion, it's not worth working on improvement for Reaktoro v1, but if anyone thinks otherwise, I'd be happy to accept a PR.
