### ISSUE TITLE
reaktoro installation problem!!

### ISSUE THREAD

**Issue by nimaamp** [reaktoro/reaktoro#185]
Hi everyone, so I'm having trouble installing reaktoro on my system, I followed the steps to reproduce as mentioned on reaktoro.org website and it is not working. I followed the anaconda process and exactly copy paste and didn't get any error while installation but when I run the command to check if it is installed to get the path, it says "no module name reaktoro".

Im new in the coding domain and just need to install to run some demo files but its not working. I tried simply opening python console and tried to import reaktoro, it gives the same error! anyone having any lead what could be wrong.
![image](https://user-images.githubusercontent.com/79060696/107888239-fb1e7280-6ed8-11eb-9363-45f496703cf3.png)

My system requirements:
Anaconda= 4.9.2
python= 3.7.9
OS= windows 10

`conda info` reproduces following:
![image](https://user-images.githubusercontent.com/79060696/107888626-944e8880-6edb-11eb-96fa-cd57b1bb1675.png)

`conda devenv`
![image](https://user-images.githubusercontent.com/79060696/107888692-f0191180-6edb-11eb-8100-fff8ca09ead0.png)

`conda activate reaktoro`
![image](https://user-images.githubusercontent.com/79060696/107888732-26ef2780-6edc-11eb-80a9-84b6d0e3487c.png)

Anyone with this issue resolved would be highly appreciated! thanks

**Comment by nimaamp** [comment]
Quick edit, the error is somewhere here i believe,
I executed these two commands to build using CMake and the output is the same saying configuration incomplete!!
`cmake -P install` and `cmake -DBUILD_PATH=C:\Users\nimaa\Desktop\reaktoro\build -P install`

![image](https://user-images.githubusercontent.com/79060696/107889185-daf1b200-6ede-11eb-8c33-557366de314f.png)

**Comment by volpatto** [comment]
Hi, @nimaamp.

Thank you for your interest in Reaktoro. Let me try to help you.

Have you found how to solve your problem? I'm asking because you closed the issue.

What is your use case for Reaktoro? Are you planning to change Reaktoro's code or just need to use it, like the Python codes examples?

Cheers,
Diego

**Comment by allanleal** [comment]
Hi @nimaamp. If you just need to use Reaktoro, then you can rely on the conda package via `conda install conda-forge::reaktoro`. It seems you also ended up trying to build Reaktoro, using cmake. And then you create the `reaktoro` environment, but this is an environment for the development of Reaktoro; not for its usage.

We can discuss your next steps in this chat room https://gitter.im/reaktoro/community

**Comment by nimaamp** [comment]
Hi @volpatto and @allanleal, thank you for your response. I was having an issue in setting and installing up the reaktoro library. For some reason, it's not getting installed. first, I had this issue with the local command line, and then I moved to google colab too. But since I haven't tried `conda install conda-forge::reaktoro` so I'll go ahead and try this one too to see if it's running!

**Comment by allanleal** [comment]
OK. You can reach me on https://gitter.im/reaktoro/community if we need further iterations to get this working on your system.
