### ISSUE TITLE
Reaktoro's workflow

### ISSUE THREAD

**Issue by alexandrebbruno** [reaktoro/Reaktoro#2]
Hi @allanleal,

Since Reaktoro is growing, I think it is a great opportunity to start thinking about the workflow that could be used inside the project. After we came into an agreement about that topic, I could create an official file and add to the project.

What do you think about the idea of using a Fork & Pull Request workflow? After we decided to work in a new Feature or fix a bug, we could create a new branch from our master fork, add all the code in that branch and, once we finish, make a PR to the reaktoro's main branch. 

Doing that, we will only have one branch inside the repo and the releases could me done by the flag system offer by github.

It is a simpler version of gitflow, because won't have any developer, but I think that could work fine. 

[]'s

**Comment by nicoddemus** [comment]
Also, we should use some of the branch protection features in GitHub, namely that PRs can only be merged if:

* At least 1 approval from maintainers.
* All CI jobs have passed.

**Comment by allanleal** [comment]
Sounds good @alexandrebbruno . Have you uploaded this file somewhere?

Could you guys please set up what @nicoddemus suggested above? Or should we do this once @alexandrebbruno has finalized his regression tests? I still need to run those - first thing tomorrow.

**Comment by nicoddemus** [comment]
We can configure the repository right away, even if CI isn't fully complete yet; admins can override this restriction if they want to.

Only repo administrators can set this up btw.

**Comment by alexandrebbruno** [comment]
> Sounds good @alexandrebbruno . Have you uploaded this file somewhere?
> 
> Could you guys please set up what @nicoddemus suggested above? Or should we do this once @alexandrebbruno has finalized his regression tests? I still need to run those - first thing tomorrow.

Sorry, I'm still working in that file.

There are only 4  test that are flaky, therefore as soon as @tadeu finish the CI integration I could mark those 4 test as xfail (just while @allanleal take a look at than). I think that have at least some of than working it will be helpful  :)

**Comment by nicoddemus** [comment]
Agree, sounds good.

**Comment by alexandrebbruno** [comment]
> Also, we should use some of the branch protection features in GitHub, namely that PRs can only be merged if

Done!
