### ISSUE TITLE
Could not load embedded database file

### ISSUE THREAD

**Issue by Edwin-OA** [reaktoro/reaktoro#222]
Hi, 

I am using the supcrt07-organics.xml database to run some DNA and protein calculations, until a couple of months ago I didn't have any problems using the database, only recently after updating my computer and reinstalling everything I started getting this error:

RuntimeError: ***ERROR***
Could not load embedded database file with name `/Desktop/SynCell/supcrt07-organics_AABB.xml`. The currently supported names are:
    - supcrt98.xml
    - supcrt07.xml
    - supcrt16.xml
    - supcrtbl.xml
    
I'm wondering if I missed anything in the installation process or if the compatibility changed recently, I have also tried using the database names suggested by the error message but won't change much.

Thanks

<img width="1055" alt="Screenshot 2021-10-15 at 23 51 15" src="https://user-images.githubusercontent.com/65565848/137591184-6f187548-56ca-4913-afa5-698a60a38487.png">

**Comment by allanleal** [comment]
Hi @Edwin-OA 

I created a very minimal script `rkt_database_test.py` (see code below) and a copy of `supcrt98-organics.xml` named `custom-supcrt98-organics.xml`. Both files are on the same directory.

**`rkt_database_test.py`**
~~~py
from reaktoro import *

db = Database("/home/allan/codes/playground/custom-supcrt98-organics.xml")
~~~

Running `python rkt_database_test.py` on my end succeeds. 

Could you please attach your xml database file? I fear there could be an error in it (but apparently you also tried with a copy of the database `supcrt98-organics.xml`, right?

Also try using `Database("custom-supcrt98-organics.xml")`, without `this_dir`, to see if it works. 

In Reaktoro v2.0 (in the making), there is a better API for what you want to do. You would write:

~~~py
db = Database.fromFile(this_dir + "/supcrt07-organics_AABB.yaml")
~~~

and the database is in YAML format, not XML anymore.

**Comment by Edwin-OA** [comment]
Hi @allanleal,

I just downloaded the supcrt98-organics.xml database and ran the same test script you created but it doesn't seem to work, same with the `Database("custom-supcrt98-organics.xml")` without `this_dir`

<img width="892" alt="Screenshot 2021-10-19 at 1 48 14" src="https://user-images.githubusercontent.com/65565848/137857949-20fa8b66-7800-42a7-916f-a0523bd66684.png">

Here is the database I am trying to use:
[supcrt07-organics_AABB.xml.zip](https://github.com/reaktoro/reaktoro/files/7370888/supcrt07-organics_AABB.xml.zip)

I really didn't see this error before until last month, but I'm afraid it may have something to do with a macOS update or the installation process.

**Comment by allanleal** [comment]
I'll close this issue then, based on the fact that it is due to accidental installation of v2 instead of v1.

**Comment by allanleal** [comment]
Hi @Edwin-OA . 

You may want to check the following tutorials to learn the new way of computing standard thermodynamic properties of species and reactions (without the `Thermo` class that existed in Reaktoro v1):

* [Computing standard thermodynamic properties of species](https://reaktoro.org/tutorials/basics/computing-thermo-props-of-species.html)
* [Computing standard thermodynamic properties of reactions](https://reaktoro.org/tutorials/basics/computing-thermo-props-of-reactions.html)

Let me know if they indeed cover your needs. These tutorials are a work in progress. Feedback welcome!
