### ISSUE TITLE
'utf-8' codec can't decode byte 0xa0 in position XXX: invalid start byte

### ISSUE THREAD

**Issue by Kanonkessen** [reaktoro/reaktoro#232]
Hello Team Reaktoro, 

I already mentionned this bug to Allan in the gitter discussion but I wanted to do a proper bug report. 
I will copy-paste my current working setup because it might be relevant to the bug I'm reporting. 

> My personnal computer runs on Windows7 (for several reasons) and is therefore on Python 3.7.11 (64 bits), my current IDE is spyder 5.2.1 and reaktoro V2 is the current most recent version : 2.0.0.rc9.
> My working computer runs on the latest Linux Mint version, with Python 3.9,9, spyder 5.2.1 and is also using Reaktoro V2.0.0rc9

*updated with the newest version of Reaktoro

**Bug description** :  When I try and print table objects (ChemicalState or ChemicalProps), I usually get a UTF-8 codec error like this one : 
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 469: invalid start byte`
This bug is not reproducible between my 2 working stations : only my personnal computer running on Win7 and python 3.7.11 s affected. The computer running on linux does not have this error in the same situation.

I will try and provide maximum information about what's happening in different examples taken from the Reaktoro V2 tutorial pages. Each example will be treated seperately in a dedicated message in this thread.

Example 1 : [Computing Chemical Properties](https://reaktoro.org/tutorials/basics/computing-chemical-properties.html)

When using this code (copy pasted from the tutorial)

```
from reaktoro import *

db = PhreeqcDatabase("phreeqc.dat")
solution = AqueousPhase(speciate("H O Na Cl C"))
system = ChemicalSystem(db, solution)

state = ChemicalState(system)
state.temperature(60.0, "celsius")
state.pressure(15.0, "atm")
state.set("H2O", 1.0, "kg")
state.set("Na+", 1.0, "mol")
state.set("Cl-", 1.0, "mol")
state.set("CO2", 0.7, "mol")
equilibrate(state)

print(state)

aquprops = AqueousProps(state)
print(aquprops)

props = ChemicalProps(state)
print(props)
```

Both the chemical state and the aqueous properties are printed as tables, but printing the ChemicalProps object return this error

```
Traceback (most recent call last):

  File "C:\Users\Kanon\AppData\Local\Temp/ipykernel_10072/1319927291.py", line 26, in <module>
    print(props)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 469: invalid start byte
```
### -----------

I tried to change the database used for calculation to `pitzer.dat` and `cemdata18` (and correcting the species name like H20@), the error returned was the same : 

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 469: invalid start byte`
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 608: invalid start byte`

respectively. Note that the error position for both 'phreeqc.dat' and 'pitzer.dat' are the same

### -----------

I also tried different methods to define the aqueous species in the solution. In the previous example, I used `speciate()`. I also tried to select the aqueous species "by hand"
`solution = AqueousPhase("H2O H+ OH- ... Na+ Cl-")`
Or by creating a list
```
aqueous_species = [
    "H2O", 
    "CaOH+", 
   ...
    "Na+", 
    "OH-"
]

solution = AqueousPhase(aqueous_species)
```
Both methods returned the same `UnicodeDecodeError` on printing ChemicalProps

### -----------

Using the following code : 
`str(props)`

return the same error
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 469: invalid start byte`

### -----------
Running the following code **in a new console** returns the ChemicalProps table without a bug

```
from reaktoro import *

db = PhreeqcDatabase("pitzer.dat")
solution = AqueousPhase(speciate("H O Na Cl C"))
system = ChemicalSystem(db, solution)

state = ChemicalState(system)
state.temperature(60.0, "celsius")
state.pressure(15.0, "atm")
state.set("H2O", 1.0, "kg")
state.set("Na+", 1.0, "mol")
state.set("Cl-", 1.0, "mol")
state.set("CO2", 0.7, "mol")
equilibrate(state)

# print(state)

# aquprops = AqueousProps(state)
# print(aquprops)

props = ChemicalProps(state)
print(props)

```

**BUT**, running `print(props)` **a second time** in the same console return the `UnicodeDecodeError`

### -----------
In a new console, printing ChemicalProps first followed by creating an output file works fine : the table and the file are displayed and created respectively

```
props = ChemicalProps(state)
print(props)
props.output("Results.txt")
```

**BUT** in a new console,  creating an output file _before_ printing ChemicalProps returns the same `UnicodeDecodeError` 
```
props = ChemicalProps(state)
props.output("Results.txt")
print(props)

```
In this case, the file is still created

NOTA BENE : when I was reviewing my output files, I did not see any strange or unusual signs or characters.

### -----------
Changing the Temperature and Pressure of the ChemicalState (slightly) changes the position of the error, for example :

```
state.temperature(250.0, "celsius")
state.pressure(250.0, "atm")
```

ChemicalProps's `UnicodeDecodeError` moves from position `469` to `471`

That's all my tests undergone in the [Computing Chemical Properties](https://reaktoro.org/tutorials/basics/computing-chemical-properties.html) example. I will post other examples for the same error on different objects later.

**Comment by Kanonkessen** [comment]
Another example of the same (?) bug but another type of object : ChemicalState

Taken from the [Chemical equilibrium with constraints](https://reaktoro.org/tutorials/equilibrium/equilibrium-specifying-constraints.html) tutorial

Slightly modified code (removed specs / condition and created another ChemicalState variable for clarity issues ) from this tutorial : 

```
from reaktoro import *

db = NasaDatabase("nasa-cea")
gases = GaseousPhase("CH4 O2 CO2 CO H2O H2")
system = ChemicalSystem(db, gases)

solver = EquilibriumSolver(system)

state0 = ChemicalState(system)
state0.set("CH4", 1.0, "mol")
state0.set("O2",  0.5, "mol")

print("INITIAL STATE")
print(state0)

state1 = ChemicalState(state0)

solver.solve(state1)

print("FINAL STATE")
print(ChemicalState(state1))

props = ChemicalProps(state1)
print(props)
```
returns : 

```
INITIAL STATE
+-----------------+--------+------+
| Property        |  Value | Unit |
+-----------------+--------+------+
| Temperature     | 298.15 |    K |
| Pressure        | 100000 |   Pa |
| Charge:         |      0 |  mol |
| Element Amount: |        |      |
| :: H            |      4 |  mol |
| :: C            |      1 |  mol |
| :: O            |      1 |  mol |
| Species Amount: |        |      |
| :: CH4          |      1 |  mol |
| :: O2           |    0.5 |  mol |
| :: CO2          |  1e-16 |  mol |
| :: CO           |  1e-16 |  mol |
| :: H2O          |  1e-16 |  mol |
| :: H2           |  1e-16 |  mol |
+-----------------+--------+------+
FINAL STATE
Traceback (most recent call last):

  File "D:\Mes Documents\Python\Tuto Reaktoro V2\untitled0.py", line 30, in <module>
    print(ChemicalState(state1))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 191: invalid start byte
```
In this case, the initial chemical state (state0) is printed properly but the final state (state1) is not.

When trying to print state0, state1 or props one more time in the same console
`print(state0)` ->`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 171: invalid start byte`
`print(state1)` ->`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 191: invalid start byte`
`print(props)` ->`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 331: invalid start byte`
 
Therefore, the bug can happen on both ChemicalState objects and ChemicalProps objects. Both follow the same patterns that were observed in [example 1](https://github.com/reaktoro/reaktoro/issues/232#issue-1112977110) :  

- Printing only works in a new console on the first object 
- Printing another object or the same object a second time in the same console returns the `UnicodeDecodeError`
- Creating an output file followed by printing an object returns the `UnicodeDecodeError`

### -----------

I tried to print several "bugged" objects at the same time in a new console, like this ;

`print(ChemicalState(state0),  ChemicalState(state1))`
results in :

```
+-----------------+--------+------+
| Property        |  Value | Unit |
+-----------------+--------+------+
| Temperature     | 298.15 |    K |
| Pressure        | 100000 |   Pa |
| Charge:         |      0 |  mol |
| Element Amount: |        |      |
| :: H            |      4 |  mol |
| :: C            |      1 |  mol |
| :: O            |      1 |  mol |
| Species Amount: |        |      |
| :: CH4          |      1 |  mol |
| :: O2           |    0.5 |  mol |
| :: CO2          |  1e-16 |  mol |
| :: CO           |  1e-16 |  mol |
| :: H2O          |  1e-16 |  mol |
| :: H2           |  1e-16 |  mol |
+-----------------+--------+------+ Traceback (most recent call last):

  File "C:\Users\Kanon\AppData\Local\Temp/ipykernel_10920/3146428695.py", line 30, in <module>
    print(ChemicalState(state0),  ChemicalState(state1))

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 191: invalid start byte
```

Interesting result. Even when I try to `print` several objects at the same time, only the first one is printed properly. Here, `state1` (position 191) isn't displayed.
I initially thought that the first `print` always displayed the "bugged" object (at least one time), but it's not true. As shown here, only the first "bugged" object is displayed . This is also consistent with the fact that creating an output file `state0.output` before making the first `print` also returns the `UnicodeDecodeError`.

**Comment by Kanonkessen** [comment]
### Conclusion : 


What I know about this bug : 

- There are 2 different types of objects. "Safe" objects can be printed and displayed properly any number of time in the same console / kernel. In example 1, the `ChemicalState` and the `AqueousState` are "safe" objects.
- In example 1, `ChemicalProps` is a "bugged" object i.e. an object related to the `UnicodeDecodeError`. In example 2, both `ChemicalState` objects and the `ChemicalProps` objects are "bugged" objects.
- Printing wether a "safe" or a "bugged" object in a new console or making an output file will bug the kernel. Enceforth, it will not be able to properly display "bugged" objects.

**Comment by allanleal** [comment]
Hi @Kanonkessen - thanks for this detailed bug report. From our discussions before, I thought this was happening with `PhreeqcDatabase` only, but now I see this happens when other databases are used (`NasaDatabase`). The issue must lie in the combination of Windows 7 and the library [tabulate](https://github.com/p-ranav/tabulate) that Reaktoro uses for pretty-printing tables. 

May I kindly ask you to try to reproduce this issue in *Windows 10*?

**Comment by Kanonkessen** [comment]
I managed to burrow a computer using Windows 10 at my work.

I started a clean install of conda, created a new environment running on Python 3.7.12 (the closest to my python setup on Windows7), installed reaktovoV2.0.0rc9 (and the packages related) and the latest version of Spyder, nothing else.

I ran the same code as example 2 : 
```
from reaktoro import *

db = NasaDatabase("nasa-cea")
gases = GaseousPhase("CH4 O2 CO2 CO H2O H2")
system = ChemicalSystem(db, gases)

solver = EquilibriumSolver(system)

state0 = ChemicalState(system)
state0.set("CH4", 1.0, "mol")
state0.set("O2",  0.5, "mol")

print("INITIAL STATE")
print(state0)

state1 = ChemicalState(state0)

solver.solve(state1)

print("FINAL STATE")
print(ChemicalState(state1))

props = ChemicalProps(state1)
print(props)
```
And I got the exact same error in the same position :
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 191: invalid start byte`

So I created ANOTHER environment with python 3.9.9, Reaktoro V2.0.0rc9, latest Spyder and tested the same code again. Guess what ?
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 191: invalid start byte`

As a result I can conclude that : 
`The UnicodeDecodeError` is not linked to the version of Windows (same exact error on Win7 and Win10)
`The UnicodeDecodeError` is not linked to the version of Python (same exact error on Python 3.7.11, 3.7.12 and 3.9.9)

Again, no bug when using Python 3.9.9 and ReaktoroV2.0.0rc9 on Linux.

Sorry but I couldn't do all the tests I reported above because I only had a brief access to the Win10 computer so I only tried to replicate example 2.

This is a much bigger issue than I anticipated. I really thought that this bug was linked to either my Win7 or Python 3.7.11 and now it appears that the bug can be reproduced on Win10 and python 3.9.9. 

I wish you the best to figure this one out @allanleal.

**Comment by allanleal** [comment]
Thanks, @Kanonkessen . Looks like we'll need to replace this tabulate library (or change some of its configs to see if this error is gone).

**Comment by Kanonkessen** [comment]
To quote a message from @allanleal in the gitter discussion : 

> 2.0.0rc13 is now out and with the UTF-8 issue fixed. This error was happening because the tabulate library that Reaktoro depends on (to have pretty tables) messes up with how numbers are printed depending on your region configuration in Windows (e.g., locale). Anyway, the bug should be gone.

I tested 2.0.0rc13 using win7 and win10 set to my region which was apparently the main cause for the bug. Version 2.0.0rc13 indeed fixed the `UnicodeDecodeError`. I will mark this issue as closed.

**Comment by allanleal** [comment]
Thanks @Kanonkessen. Please don't hesitate to report bugs.
