### ISSUE TITLE
Reaktoro usage can be even simpler with reaktoro.easy Python module

### ISSUE THREAD

**Issue by allanleal** [reaktoro/reaktoro#24]
# Motivation

Currently, the user needs to be know a few to many Reaktoro components to perform any calculation. For example, the user needs to understand how to create and operate objects of classes `ChemicalEditor`, `ChemicalSystem`, `ChemicalState`, `EquilibriumProblem`, and others to perform even the simplest calculations.

This proposal aims to simplify Reaktoro's usage as suggested in the self-explanatory examples below.

# Examples

### Current and more advanced approach

~~~python
from reaktoro import *

editor = ChemicalEditor()
editor.addAqueousPhase('H2O NaCl CO2')
editor.addGaseousPhase(['H2O(g)', 'CO2(g)'])

system = ChemicalSystem(editor)

problem = EquilibriumProblem(system)
problem.setTemperature(100, 'celsius')
problem.setPressure(300, 'bar')

problem.add('H2O', 1, 'kg')
problem.add('NaCl', 1, 'mol')
problem.add('CO2', 1, 'mol')

state = equilibrate(problem)
state.output('state.csv')
~~~

### Simplified approach

~~~python
from reaktoro.easy import *

equilibrium.temperature(100, 'celsius')
equilibrium.pressure(300, 'bar')

equilibrium.add('H2O', 1, 'kg')
equilibrium.add('NaCl', 1, 'mol')
equilibrium.add('CO2', 1, 'mol')

equilibrium.solve()
equilibrium.output('state.csv')
~~~

### Simplified approach

~~~python
from reaktoro.easy import *

equilibrium.temperature(100, 'celsius')
equilibrium.pressure(300, 'bar')

equilibrium.add('H2O', 1, 'kg')
equilibrium.add('NaCl', 1, 'mol')

state1 = equilibrium.solve()

equilibrium.add('CO2', 1, 'mol')

state2 = equilibrium.solve()

state1.output('state1.csv')
state2.output('state2.csv')

equilibriumpath.initialstate(state1)
equilibriumpath.finalstate(state2)
equilibriumpath.collect.temperature()
equilibriumpath.collect.elementAmount('C')
equilibriumpath.collect.pH()
equilibriumpath.solve()
equilibriumpath.output('states.csv')
~~~

**Comment by alexandrebbruno** [comment]
Great idea, simplify Reaktoro's usage could really help some beginners which want use the framework but don't have time to understand all the classes. I would love to help with that on my free time ;)

Only one thing is not totally clear. Do you thinking that we should offer the same functionally for bought module?

One idea is just create some new binds for that new Python modules, but by doing that we only offers that new functionally for Python. The problem is that we will only have this options for Pythons users. Do you have any ideia about how we could do something similar for C++?

**Comment by allanleal** [comment]
C++ users would not benefit from this simple usage, you're right, and maybe **this is not the right decision**. Perhaps we could then implement this feature in C++ and then wrap it in Python (using pybind11). This would permit this simple calculation usage for both C++ and Python users.

Note, however, that the initial thought would be to allow Python users to use, say, `ipython` and perform calculations more interactively. This interactive mode is not possible in C++ in general.

The implementation would require some additional C++ classes. For example, an `Equilibrium` class in a namespace `Reaktoro::easy`. Not sure yet about the need for the namespace. Then, in a header file `Reaktoro/Easy.hpp`, we would have a global variable `equilibrium` (an object of `Equilibrium`).

~~~c++
#include <Reaktoro/Easy.hpp>
using namespace Reaktoro::easy;

int main()
{
    equilibrium.temperature(100, "celsius");
    equilibrium.pressure(300, "bar");

    equilibrium.add("H2O", 1, "kg");
    equilibrium.add("NaCl", 1, "mol");
    equilibrium.add("CO2", 1, "mol");

    equilibrium.solve();
    equilibrium.output("state.csv");
}
~~~

We would need to stress that this simpler usage mode is not for **critical computations** in which Reaktoro is coupled with other codes (say, for reactive transport simulations). These users are in general more advanced C++ programmers and they are perfectly capable of understanding the use of Reaktoro classes and methods.

**Comment by alexandrebbruno** [comment]
Got it :)
At first I thought that we could rewrite the entire API, but it will take a huge effort and break backward compatibility. This simplified option with the correct binds will be much better.
As soon as I have some free time I will start working on it, if you don't mind :)

**Comment by nicoddemus** [comment]
Hi everyone,

Just to leave my 2 cents: I like the idea of providing an easy to use API for interactive usage, but in general I really dislike having global variables. I think we can keep almost the same API while also avoiding having globals as part of the API, as some users might miss the point and use it while coupling Reaktoro with their applications.

So if you folks think this is something we should care about, I propose changing the API slightly:

```C++
#include <Reaktoro/Easy.hpp>
using namespace Reaktoro::easy;

int main()
{
    equilibrium = EasyEquilibriumSolution();
    equilibrium.temperature(100, "celsius");
    equilibrium.pressure(300, "bar");

    equilibrium.add("H2O", 1, "kg");
    equilibrium.add("NaCl", 1, "mol");
    equilibrium.add("CO2", 1, "mol");

    equilibrium.solve();
    equilibrium.output_csv("state.csv");
}
```

An alternative step to create the object seems like a cheap price to pay here. 😁 

Alternatively, we might only implement this as a Python module: this might make it more explicit that it is meant to be used interactively and not for production. Plus it would be easier/quicker to implement.

**Comment by allanleal** [comment]
@alexandrebbruno Great - thanks for your offer!

@nicoddemus I agree in avoiding global variables. Instead of `EasyEquilibriumSolution` class, which is more specific to equilibrium calculations only, we could have a class `Rkt` (or some other name):

## C++
~~~c++
#include <Reaktoro/Reaktoro.hpp>
using namespace Reaktoro;

int main()
{
    Rkt rkt;
    rkt.temperature(100, "celsius");
    rkt.pressure(300, "bar");

    rkt.add("H2O", 1, "kg");
    rkt.add("NaCl", 1, "mol");
    rkt.add("CO2", 1, "mol");

    rkt.equilibrate();
    rkt.outputCSV("state.csv");
}
~~~

## Python
~~~python
from reaktoro import Rkt

rkt = Rkt()
rkt.temperature(100, 'celsius')
rkt.pressure(300, 'bar')
rkt.add('H2O', 1, 'kg')
rkt.add('NaCl', 1, 'mol')
rkt.add('CO2', 1, 'mol')
rkt.equilibrate()
rkt.outputCSV('state.csv')
~~~

**Comment by allanleal** [comment]
In the meanwhile other technologies have emerged, and focus will be given to other more convenient approaches. Stay tuned!
