### ISSUE TITLE
reaktoro does not compile

### ISSUE THREAD

**Issue by eric-methorst** [reaktoro/reaktoro#249]
I just cleaned up the entire system: removed miniconda and reaktoro and started again from stratch.
So I installed the latest miniconda: conda --version gives: conda 4.12.0
followed the installation instructions and got the latest reaktoro sources from github, installed them in ~/dev/reaktoro2
did the cmake -P install
got:
-- Found autodiff: /home/eme/miniconda3/envs/reaktoro/lib/cmake/autodiff (found version "0.6.8")
-- Found Eigen3: /home/eme/miniconda3/envs/reaktoro/share/eigen3/cmake (found version "3.3.90")
-- Found nlohmann_json: /home/eme/miniconda3/envs/reaktoro/lib/cmake/nlohmann_json (found version "3.10.5")
-- Found Optima: /home/eme/miniconda3/envs/reaktoro/lib/cmake/Optima (found version "0.2.6")
-- Found phreeqc4rkt: /home/eme/miniconda3/envs/reaktoro/lib/cmake/phreeqc4rkt (found version "3.6.2.1")
-- Found ThermoFun: /home/eme/miniconda3/envs/reaktoro/lib/cmake/ThermoFun (found version "0.3.8")
-- Found yaml-cpp: /home/eme/miniconda3/envs/reaktoro/share/cmake/yaml-cpp (found version "0.6.3")
CMake Error at cmake/ReaktoroFindDeps.cmake:21 (find_package):
  Could not find a configuration file for package "Catch2" that is compatible
  with requested version "2.6.2".

  The following configuration files were considered but not accepted:

    /home/eme/miniconda3/envs/reaktoro/lib/cmake/Catch2/Catch2Config.cmake, version: 3.0.1

Call Stack (most recent call first):
  cmake/ReaktoroFindDeps.cmake:39 (ReaktoroFindPackage)
  CMakeLists.txt:89 (include)

**Comment by eric-methorst** [comment]
Hi Allen,
It does not change anything. When I run ‘cmake -S . -B build’ I get he exact same error.
The problem is not the -P install, as it doesn’t even get close to that is in the most initial phase when it tries to resolve the dependencies and cannot resolve Catch2 because some package want version 2.6.2 while the one provided is 3.0.1
(reaktoro) ***@***.***:~/dev/reaktoro2$ cmake -S . -B build
-- CCache: Found ccache installed.
-- CCache: Using ccache to potentially speed up the build operation.
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/eme/miniconda3/envs/reaktoro/bin/x86_64-conda-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CondaAware: Conda environment detected!
-- CondaAware: Found environment variable CONDA_PREFIX=/home/eme/miniconda3/envs/reaktoro
-- CondaAware: Setting PYTHON_EXECUTABLE=/home/eme/miniconda3/envs/reaktoro/bin/python
-- CondaAware: Set CONDA_AWARE_PREFIX=/home/eme/miniconda3/envs/reaktoro
-- CondaAware: Setting CMAKE_INSTALL_PREFIX=CONDA_AWARE_PREFIX=/home/eme/miniconda3/envs/reaktoro
-- CondaAware: Appended /home/eme/miniconda3/envs/reaktoro to CMAKE_PREFIX_PATH
-- CondaAware: Appended /home/eme/miniconda3/envs/reaktoro/include to include directories
-- CondaAware: Appended /home/eme/miniconda3/envs/reaktoro/lib to link directories
-- Setting build type to Release as none was specified.
-- Found autodiff: /home/eme/miniconda3/envs/reaktoro/lib/cmake/autodiff (found version "0.6.8")
-- Found Eigen3: /home/eme/miniconda3/envs/reaktoro/share/eigen3/cmake (found version "3.3.90")
-- Found nlohmann_json: /home/eme/miniconda3/envs/reaktoro/lib/cmake/nlohmann_json (found version "3.10.5")
-- Found Optima: /home/eme/miniconda3/envs/reaktoro/lib/cmake/Optima (found version "0.2.6")
-- Found phreeqc4rkt: /home/eme/miniconda3/envs/reaktoro/lib/cmake/phreeqc4rkt (found version "3.6.2.1")
-- Found ThermoFun: /home/eme/miniconda3/envs/reaktoro/lib/cmake/ThermoFun (found version "0.3.8")
-- Found yaml-cpp: /home/eme/miniconda3/envs/reaktoro/share/cmake/yaml-cpp (found version "0.6.3")
CMake Error at cmake/ReaktoroFindDeps.cmake:21 (find_package):
  Could not find a configuration file for package "Catch2" that is compatible
  with requested version "2.6.2".

  The following configuration files were considered but not accepted:

    /home/eme/miniconda3/envs/reaktoro/lib/cmake/Catch2/Catch2Config.cmake, version: 3.0.1

Call Stack (most recent call first):
  cmake/ReaktoroFindDeps.cmake:39 (ReaktoroFindPackage)
  CMakeLists.txt:89 (include)


So somewhere I got a version conflict on this Catch2 package

PS, running on kubunu: uname -a
Linux kubuntu 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Regards, Eric

**Comment by allanleal** [comment]
Right. It seems like catch2 upgraded to a new major version (v3) and the conda environment is being created with it. Could you please try, in the [environment.devenv.yml](https://github.com/reaktoro/reaktoro/blob/main/environment.devenv.yml) file, replacing the line: 

~~~yaml
  - catch2
~~~
by
~~~yaml
  - catch2=2.6
~~~

and then running `conda-devenv` again?

**Comment by eric-methorst** [comment]
Hi Alan,

I tried as you suggested, and when I set the version number to 2.6 it did:
Downloading and Extracting Packages
certifi-2022.5.18.1  | 150 KB    | ##...### | 100%
pandas-1.4.2         | 12.5 MB   | ####...### | 100%
zlib-1.2.12          | 90 KB     | ####...## | 100%
graphviz-4.0.0       | 2.7 MB    | ###..## | 100%
python-3.9.13        | 26.7 MB   | ###...### | 100%
cmake-3.23.2         | 16.3 MB   | ####...### | 100%
libzlib-1.2.12       | 62 KB     | ####...#### | 100%
catch2-2.6.1         | 140 KB  | ####...#### | 100%

please note this is the wrong version.
As a consequence we I get after the cmake instruction:
-- Found yaml-cpp: /home/eme/miniconda3/envs/reaktoro/share/cmake/yaml-cpp (found version "0.6.3")
CMake Error at cmake/ReaktoroFindDeps.cmake:21 (find_package):
  Could not find a configuration file for package "Catch2" that is compatible
  with requested version "2.6.2".

  The following configuration files were considered but not accepted:

    /home/eme/miniconda3/envs/reaktoro/lib/cmake/Catch2/Catch2Config.cmake, version: 2.6.1

Call Stack (most recent call first):
  cmake/ReaktoroFindDeps.cmake:39 (ReaktoroFindPackage)
  CMakeLists.txt:89 (include)

So I tried again, setting the catch2=2.6.2 this time in the environment.devenv.yml and got:
Executing: conda env update --file /home/eme/dev/reaktorov2/environment.yml --prune
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - catch2=2.6.2

I’ve had a look at the Catch2 github and by the looks of it, that version does not even exist:
***@***.***

Some package out there really wants that 2.6.2 version, while it doesn’t exist.
So what needs to be done to fix this?
And why is it only broken for me? Is this a Kubuntu issue?

Regards, Eric

PS does it matter if I run conda-devenv from an activated reaktoro environment?

**Comment by allanleal** [comment]
This commit resolves the issue above:
https://github.com/reaktoro/reaktoro/commit/ed4bb6bcbe5bc8dca49a596e7d2bde10b84f2255

Please try again and reopen if you still have issues.
