### ISSUE TITLE
Considering reagent flow during calculations

### ISSUE THREAD

**Issue by rafaelaugustoalves** [reaktoro/reaktoro#25]
Does Reaktoro support reagent flow during calculations to allow geochemical modelling in a Pore Network Model?

It should be possible to simulate reaction at each individual pore for a given period of time as a 'static' process and after this time interval change concentrations at pores based on flow. However, it seems likely that the flow itself interferes considerably with reactions velocity, in which case it's necessary to consider flow during calculations.

**Comment by allanleal** [comment]
Reaktoro provides methods for chemical equilibrium and chemical kinetics calculations. Fluid flow calculations (in any medium of interest) needs to be performed by the user. 

You might want to apply an operator splitting scheme in which you first update concentrations based on transport processes alone (e.g., advection, diffusion), and in a subsequent step you use Reaktoro to incorporate the chemical reactions among fluid species and rock minerals. 

If the rates of reactions are considerably faster than the rates of transport, then an equilibrium calculation in each pore should suffice. If some reactions (e.g., some mineral dissolution reactions) have rates not that substantially faster than the other processes, then a combination of equilibrium and kinetics calculations is needed. 

Have a look in Section 4 of the attached paper:

[Leal et al. - 2017 - An overview of computational methods for chemical equilibrium and kinetic calculations for geochemical and reactive.pdf](https://github.com/reaktoro/reaktoro/files/2548418/Leal.et.al.-.2017.-.An.overview.of.computational.methods.for.chemical.equilibrium.and.kinetic.calculations.for.geochemical.and.reactive.pdf)

**Comment by rafaelaugustoalves** [comment]
I will look into it, thanks for the help
