### ISSUE TITLE
Pip installation not working

### ISSUE THREAD

**Issue by eduardo-rd** [reaktoro/reaktoro#251]
Reaktoro is not currently working when installed by pip from PyPI. It does succesfully pull all dependencies and the `reaktoro-1.2.1-py3-none-any` wheel. But when trying to import it gives the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/venv/python3.9/site-packages/reaktoro/__init__.py", line 1, in <module>
    from reaktoro.PyReaktoro import *
ModuleNotFoundError: No module named 'reaktoro.PyReaktoro'
```

This was tested with

- Debian 11 Bullseye
- Python 3.9.2

**Comment by allanleal** [comment]
Hi @eduardo-rd - pip is not currently officially supported. Please use conda as detailed [here](https://reaktoro.org/installation/installation-using-conda.html).

**Comment by eduardo-rd** [comment]
Thanks for the reply. I understand, I think it should be removed from PyPI in that case.

**Comment by allanleal** [comment]
Yes, I agree. I've just removed it from PyPi. Thanks.
