### ISSUE TITLE
Compilation error:  recompile with -fPIC

### ISSUE THREAD

**Issue by eric-methorst** [reaktoro/reaktoro#252]
[ 42%] Building CXX object Reaktoro/CMakeFiles/Reaktoro.dir/Thermodynamics/Water/WaterThermoPropsUtils.cpp.o
[ 42%] Building CXX object Reaktoro/CMakeFiles/Reaktoro.dir/Thermodynamics/Water/WaterUtils.cpp.o
[ 42%] Building CXX object Reaktoro/CMakeFiles/Reaktoro.dir/Utils/Material.cpp.o
[ 43%] Linking CXX shared library libReaktoro.so
/usr/bin/ld: ../databases/libReaktoroDatabases.a(lib.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN4cmrc17ReaktoroDatabases9res_chars27f_af3b_CMakeLists_txt_beginE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [Reaktoro/CMakeFiles/Reaktoro.dir/build.make:2102: Reaktoro/libReaktoro.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:410: Reaktoro/CMakeFiles/Reaktoro.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

intersting detail, if I look at my environment I can see that CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/eme/miniconda3/envs/reaktoro/include
-fPIC is in there.

Do I need to clean something before compiling again? I did remove the build folder before running cmake again

**Comment by allanleal** [comment]
Are you rigorously following the instructions here:
https://reaktoro.org/installation/installation-using-cmake.html

The last three builds done by GitHub (for Windows, Linux, macOS) are passing after that fix on the catch2 dependency. See this link: https://github.com/reaktoro/reaktoro/actions

**Comment by eric-methorst** [comment]
Did the following from reaktorov2 root folder:
rm -rf build
cmake -S . -B build
cmake --build build
This does eventually compile. Note that I had to leave out the --parallel
uname -a:
Linux kubuntu 5.13.0-44-generic https://github.com/reaktoro/reaktoro/issues/49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by allanleal** [comment]
OK, thanks for reporting back. So, from what you wrote above I conclude that all is fine then. I'll close this then.

**Comment by eric-methorst** [comment]
Hi Alen.

I recommend you add this to the FAQ, Tips&Tricks or whatever you have for others as a possible solution.

Regards, Eric

**Comment by eric-methorst** [comment]
Hi Alan,

I have no idea. We are running on one of the latest versions of kubuntu (uname gives: Linux kubuntu 5.13.0-44-generic #49~20.04.1-Ubuntu)
We initially started with Reaktoro v1, to add the ssp model. That was left for a while after januari, then we returned to it and we suddenly got link errors (not having touched the machine at all as far as we can tell).
This, I can reproduce now again:
[output]
/home/eme/miniconda3/envs/reaktoro-v1/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/eme/miniconda3/envs/reaktoro-v1/lib/libstdc++.so: undefined reference to ***@***.***_2.14'
/home/eme/miniconda3/envs/reaktoro-v1/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/eme/miniconda3/envs/reaktoro-v1/lib/libstdc++.so: undefined reference to ***@***.***_2.16'
/home/eme/miniconda3/envs/reaktoro-v1/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/eme/miniconda3/envs/reaktoro-v1/lib/libstdc++.so: undefined reference to ***@***.***_2.17'
collect2: error: ld returned 1 exit status
make[2]: *** [interpreter/CMakeFiles/ireaktoro.dir/build.make:86: bin/ireaktoro] Error 1
make[1]: *** [CMakeFiles/Makefile2:1419: interpreter/CMakeFiles/ireaktoro.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
(reaktoro-v1) ***@***.***:~/dev/reaktorov1$ konsole&
[/output]

As you can see I have downloaded reaktoro into my dev/reaktoro-v1 directory and activated reaktoro-v1 environment
So we decided to first have a look if we could even build version 2, as Wouter wants to upgrade to that version in the future. As my environment seemed to be a bit broken, I simply deleted the reaktoro-2 folder and cloned it from git again. Then I deleted the miniconda folder, removed the lines it had added from my bashrc and reinstalled miniconda (googled that bit: not sure if there are any other local folders I should have removed).
Then I followed the instrcutions from the website: doing the conda devenv, conda activate and the cmake.
That was when I ran into the Catch2 issue. Once that was resolved and I pulled the latest version from git, cmake would run, so I followed it up with the ‘cmake –build build/ --parallel’, which went fine up to about 48%, then I got kicked out of the machine and could not get back in. Turned out it was very slow because it was spawning build processes which it killed straight away. After about 15 I could get back in with PuTTy. I deleted the build folder (standard procedure now 0before I start a build on reaktoro) and ran it without –parallel which restarted at 17% or so and failed with the -fPIC error again.
The final time I removed the build folder again (rm -rf build/) ran ‘cmake –build build –target clean’, cmake -S . –build build’, cmake clean again and finally ‘cmake –build build/’. That last one I ran overnight and this morning it had finally compiled.

We will have to retry this on a fresh account to see if it will build or not.

So now the version 2 seems to build if I don’t use –parallel and we have to figure out why we get the glic link errors.

Regards, Eric

**Comment by eric-methorst** [comment]
HI Alen,

Thanks, that seems to have don the trick. I did channel add again, ran ‘conda devenv’ before cleaning the system and building again and it now builds.

Regards, Eric

**Comment by allanleal** [comment]
Hi Eric, great, thanks for letting me know that this fixed!
