### ISSUE TITLE
Python support install issue on xUbuntu 18.04

### ISSUE THREAD

**Issue by jdelorty** [reaktoro/reaktoro#26]
Installation of Reaktoro (on /opt/, user privileges OK) on __xUbuntu 18.04__ works fine : C++ demos are compiled normally and can be executed with no error. 
Issue comes when compiling Reaktoro with __python__ support. Following error is output :

[reaktoro_error.log](https://github.com/reaktoro/reaktoro/files/2572805/reaktoro_error.log)

All required packages found in the installation instructions at [reaktoro](http://reaktoro.org/installation.html) are installed. __pybind11-dev__ package is additionally installed.
Build procedure is as follows, in /opt/ :

$ git clone https://github.com/reaktoro/reaktoro
$ cd reaktoro && mkdir build && cd build
$ cmake .. -DBUILD_PYTHON=ON
$ sudo make -j3 install

Thanks !

**Comment by allanleal** [comment]
What is the pybind11 version you have installed?

**Comment by jdelorty** [comment]
The pybind11 version installed is **2.0.1-4** as shown below:

*$ apt show pybind11-dev 

> Package: pybind11-dev
> Version: 2.0.1-4
> Priority: optional
> 
> Section: universe/libdevel
> Source: pybind11
> Origin: Ubuntu
> Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
> Original-Maintainer: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
> Bugs: https://bugs.launchpad.net/ubuntu/+filebug
> Installed-Size: 391 kB
> Suggests: libeigen3-dev, pybind11-doc
> Homepage: https://github.com/pybind/pybind11
> Download-Size: 72,8 kB
> APT-Manual-Installed: yes
> APT-Sources: http://fr.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
> Description: seamless operability between C++11 and Python
>  pybind11 is a lightweight header library that exposes C++ types in
>  Python and vice versa, mainly to create Python bindings of existing C++
>  code. Its goals and syntax are similar to the excellent Boost.Python
>  library by David Abrahams: to minimize boilerplate code in traditional
>  extension modules by inferring type information using compile-time
>  introspection.
>  .
>  This package provides the header-only library.*

**Comment by allanleal** [comment]
This version is relatively old. Try installing pybind11 by git cloning it's
master branch, then:

~~~
mkdir build
cd build
cmake ..
sudo make install
~~~

Best is to remove the pybind11 package you have in your system first. Let
us know if this fix your issue. An improved solution for automatic
installation of external dependencies will be implemented soon.

>

**Comment by jdelorty** [comment]
For some reason cloning the pybind11 repository and compiling it right away did not work. I thus checked out the repo to the "stable" version, and reinstalled reaktoro right afterwards. 
Note also that reaktoro looks for pybind11 headers in `usr/` whereas a classic compiling of pybind11 would isntall them to `usr/local`. 
All in all this gives something like : 
`git clone https://github.com/pybind/pybind11.git pybind11
cd pybind11
git checkout stable
mkdir build && cd build
cmake ..
sudo make -j3 install

git clone https://github.com/reaktoro/reaktoro.git
cd reaktoro
mkdir build && cd build
cmake .. -DBUILD_PYTHON=ON -DBUILD_DEMOS=ON
sudo make -j3 install
`
Finally note that this was installed in the `opt/` folder, and thus some ownership issues might appear, that can be worked around with `sudo chown username clonedrepo`.

**Comment by allanleal** [comment]
With the merge #32 , this is fixed. Let us know if other issues arise.
