### ISSUE TITLE
Compile problem on windows: missing dependency tabulate

### ISSUE THREAD

**Issue by Jarnovr** [reaktoro/reaktoro#265]
Hi

I'm trying to build the latest reaktoro on windows using cmake from source.
I have build all the dependencies, but reaktoro can't build as it complains it can't find 'tabulate/table.hpp'

it seems there is a dependency that is not explicitly marked (i guess part of system packages on your linux machine).
I build tabulate and added it as package to find in cmake and added it to the target_link_libraries for reaktoro.

Then i run into a link time dependency on pugixml. I can't find any source reference to it, so I wonder if it is actually required and removing the link reference seems to work.

The next problem was that linking against phreeqc4rkt failed as that libary didn't have the symbols exported. Adding 
`set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS TRUE)` in the phreeqc4rkt\src\CMakeLists.txt seems to work.

**Comment by allanleal** [comment]
Hi Jarno, thanks for reporting this and instructing on necessary changes. I have created a pull request above addressing the above issues.

**Comment by Jarnovr** [comment]
That is a fast turn-around time. thanks.
