### ISSUE TITLE
Using Conda to manage the external dependencies of Reaktoro

### ISSUE THREAD

**Issue by allanleal** [reaktoro/reaktoro#33]
Let's use conda-forge to manage all dependencies of Reaktoro. 

Below is a list of all external libraries we need to compile Reaktoro that are already available in conda-forge. 

- json (https://anaconda.org/conda-forge/nlohmann_json)
- CVODE (https://anaconda.org/conda-forge/sundials)
- Boost (https://anaconda.org/anaconda/boost)
- pugixml (https://anaconda.org/conda-forge/pugixml)
- Eigen (https://anaconda.org/conda-forge/eigen)
- pybind11 (https://anaconda.org/conda-forge/pybind11)

The other dependencies not yet in conda-forge are:

- miniz (https://github.com/richgel999/miniz)
- gems
- phreeqc

The later two might make more sense to handle using `git submodule` as I sometimes change them.

**Comment by nicoddemus** [comment]
I've opened a PR for `nlohmann_json`: https://github.com/conda-forge/staged-recipes/pull/7575.

**Comment by nicoddemus** [comment]
Actually the feedstock already exists: https://github.com/conda-forge/nlohmann_json-feedstock

**Comment by nicoddemus** [comment]
I think we can leave it open actually, it nicely tracks our external dependencies and which are the ones available as packages already.

**Comment by allanleal** [comment]
OK - agree!

**Comment by volpatto** [comment]
JSON is addressed in #155.

**Comment by allanleal** [comment]
This issue has now been solved in [Reaktoro v2](reaktoro.org), with all dependencies obtained from conda. There is no external dep packaged with Reaktoro anymore. Thanks all for the discussion and suggestions.
