### ISSUE TITLE
pybinder installation error

### ISSUE THREAD

**Issue by simulkade** [reaktoro/reaktoro#36]
I cloned the repository and tries to install it with `cmake .. -DCMAKE_BUILD_TYPE=Release`, but I get the following error:
```
-- Boost version: 1.65.1
-- pybind11 v2.3.dev0
CMake Error at python/CMakeLists.txt:8 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/ali/packages/reaktoro/build/CMakeFiles/CMakeOutput.log".
```

Any help is appreciated.

**Comment by allanleal** [comment]
Hi! Have you installed `pybind11` already?

You are invited to check this new installation guide here:
https://reaktoro.readthedocs.io/en/latest/installation.html

It is not documented there yet (just started writing this documentation using readthedocs), but you could also try:

`conda install -c conda-forge reaktoro` (Windows)
`conda install -c conda-forge/label/gcc7 reaktoro` (Linux)

macOS will soon be supported too.

Note that you'll need to install miniconda (as explained in that guide).

**Comment by simulkade** [comment]
Thanks a lot Allan! I give it a try now.

**Comment by simulkade** [comment]
Both `cmake` and `conda` installations worked for me. Thanks again :-)

**Comment by allanleal** [comment]
Great - thanks Ali.
