### ISSUE TITLE
Unable to install reaktoro=1 with miniconda on an M2 Mac

### ISSUE THREAD

**Issue by vancesteven** [reaktoro/reaktoro#413]
with a new conda env with python=3.7, conda install reaktoro=1 gives:

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package reaktoro-1.1.1-py36hb52bf12_1 requires boost >=1.74.0,<1.74.1.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
└─ reaktoro 1**  is not installable because there are no viable options
   ├─ reaktoro [1.0.7|1.1.0] would require
   │  └─ boost >=1.70.0,<1.70.1.0a0 , which conflicts with any installable versions previously reported;
   ├─ reaktoro [1.1.0|1.1.1|1.2.0] would require
   │  └─ boost >=1.72.0,<1.72.1.0a0 , which conflicts with any installable versions previously reported;
   └─ reaktoro [1.1.1|1.2.0|1.2.2|1.2.3] would require
      └─ boost >=1.74.0,<1.74.1.0a0 , which conflicts with any installable versions previously reported.

**Comment by vancesteven** [comment]
However, conda install boost=1.74
Channels:
 - soumith
 - anaconda-fusion
 - defaults
 - conda-forge
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package boost-1.74.0-py39hc9c7e7f_2 is excluded by strict repo priority

**Comment by vancesteven** [comment]
FIXED with conda install -c conda-forge boost=1.74.0

**Comment by allanleal** [comment]
Hi Steve. Happy to help you on a smooth transition from v1 to v2. conda-forge builds for v1 have been discontinued. 

I'll close this issue as it seems you found a way to get v1 installed via conda. Otherwise, let me know.
