### ISSUE TITLE
supercritical water properties - aqueous phase volume going negative at 400 C with supcrtbl and ActivityModelHKF

### ISSUE THREAD

**Issue by Eisenh** [reaktoro/reaktoro#420]
I have the following code that attempts to simulate precipitation of minerals from sub- and supercritical water. It prints out the aqueous phase volume as it iterates through a temperature range from 300 to 450 C. Near 400 C, the volume goes negative. Is this a bug, or am I using the wrong setup?
```python
from reaktoro import *
import numpy as np
import pandas as pd
import os

# Load the SUPCRTBL database
db = SupcrtDatabase("supcrtbl")
solution = AqueousPhase(speciate("C H O Fe Na P Mg Ca S Cl K"))
solution.set(ActivityModelHKF())
deposit = MineralPhases()
#deposit.set(ActivityModelIdealSolution(StateOfMatter.Solid))
system = ChemicalSystem(db, solution, deposit)

state = ChemicalState(system)
state.set("H2O(aq)", 1.0, "kg")  #ppmw is mg
# state.set("KOH(aq)", 0.01, "mol")
#state.set("CO2(aq)", 2, "mol")
state.set("K+", 57.500, "g")
# state.set("CO3-2", 0.05, "mol")  # 2:1 stoich w K+
# Mg+2 Ca+2 H3PO4(aq) MgCO3(aq) CaCO3(aq) CaSO4(aq)
state.set("Mg+2", 0.0010, "g")
state.set("Ca+2", 0.004, "g")
state.set("Fe+3", 0.0010, "g")
state.set("Na+", 67.200, "g")
state.set("PO4-3", 0.0010, "g")
state.set("CO2(aq)", 1.0, "g")  # just a guess

# Define a range of temperatures
temperatures = np.linspace(300, 450, 100)  # Temperatures in Celsius
state.setTemperature(temperatures[0], "C")
print("T: ",temperatures[0], " C")
state.setPressure(330, "bar")

# Define the equilibrium solver and solve the equilibrium problem with the initial chemical state
solver = EquilibriumSolver(system)
solver.solve(state)
print("initial state charge imbalance", state.charge())
#state.set("OH-", state.charge(), "mol")
#state.set("CO3-2", state.charge()/2, "mol")
state.set("CO3-2", state.charge()/2, "mol")
solver.solve(state)
print("first balance state charge imbalance", state.charge())
state.add("HCO3-", state.charge(), "mol")
solver.solve(state)  
print("Balanced state charge imbalance", state.charge())
print("Number of species in the system:", system.species().size())
print("Number of phases in the system:", system.phases().size())
#print(state)
#print("before", AqueousProps(state))

# Store all properties in a list of dictionaries
data = []
# all_phases = phase.name() for phase in system.phases().findWithStateOfMatter("Solid") 

for temp in temperatures:
    state.setTemperature(temp, "C")
    result = solver.solve(state)
    if result.succeeded():
        species_amounts = state.speciesAmounts()
        props = ChemicalProps(state)
        aprops = AqueousProps(state)
        row = {"Temperature (C)": temp,
            "Ionic Strength (mol/L)": aprops.ionicStrength(),
            "pH": aprops.pH(),
            "Volume (kg/m³)": props.volume(),
            #"Saturation Index": aprops.saturationIndex(),
            "Specific Enthalpy (J/mol)": props.specificEnthalpy(),
            "Specific Entropy (J/mol.K)": props.specificEntropy(),
            #"Species Amounts": species_amounts,
            }
        for idx, species in enumerate(system.species()):
            amount = species_amounts[idx]
            row[species.name()] = amount 

        for phase in system.phases():
            phase_name = phase.name()
            
            phase_props = props.phaseProps(phase_name)
            if phase_name == "AqueousPhase":
                print(temp, " C, volume : ",phase_props.volume())
            row[f"{phase_name}_mass (kg)"] = phase_props.mass() if phase_props else 0.0
            row[f"{phase_name}_volume (m³)"] = phase_props.volume() if phase_props else 0.0
            row[f"{phase_name}_density (kg/m³)"] = phase_props.mass()/phase_props.volume() if phase_props else 0.0
        data.append(row)
        
    else:
        data.append({"Temperature (C)": temp})

# Convert to DataFrame for easier manipulation
df = pd.DataFrame(data)
# Specify the file path
file_path = os.getcwd() + "/chemical_properties.csv"

#df.to_csv(file_path, index=False)  # Save for later use


#print("After: ",AqueousProps(state))
```

**Comment by allanleal** [comment]
Hi @Eisenh, thank you for sharing your script. It seems the issue may stem from the conditions under which the molar volume of the aqueous phase is estimated. Specifically, the standard-state HKF model appears to be producing a negative molar volume, even though the molar volume of pure water, as calculated via the Wagner-Pruss EOS, is positive.

In your setup, the molar volume of the phase is approximated as:

$$V = \sum_i x_i V_i^\circ$$

Here, $x_i$ is the mole fraction of aqueous species $i$, and $V_i^\circ$ is its standard-state molar volume derived from the HKF model, which depends on $T$ (temperature) and $P$ (pressure). It seems the negative contributions from certain solutes outweigh the positive contribution from H2O(aq), resulting in an overall negative value.

This behavior suggests that the HKF model may not have been calibrated for the specific temperature, pressure, and composition conditions in your simulation. Consequently, the estimates might be inaccurate to the point of being physically invalid.

If the dependency of density and molar volume on solute concentrations is not critical for your application, you could consider approximating these properties using those of pure water instead. This simplification can avoid such inconsistencies while still providing reasonable results for many applications. In that case, you can use, for example, 

~~~py
props.speciesStandardVolume("H2O(aq)")
~~~

to get the molar volume of the water species computed by Wagner-Pruss EOS.

What do you think?

**Comment by Eisenh** [comment]
Thanks for that Suggestion.
`props.speciesStandardVolume("H2O(aq)") `
does indeed monotonically increase with temperature, which is reassuring. However, I am surprised the HKF model correlations would be that far off at these temperatures. I thought is was suitable for supercritical water, but I guess not with ions.  Should I be concerned with the equilibria calcs because of that?

On review, I suppose I should use a better EOS like Pitzer, given that I need to consider ionic strength.
I found a partial implementation of Pitzer-Sterner (for pure water) at https://github.com/forsterite/fugacity/blob/master/fugacity.py
It gives similar volumes to the Wagner-Pruss volume from my current code (within 1%), but that is without the ionic corrections).  An implementation of SupPHREEQC would be nice, LOL. I need to be fairly accurate with scaling a boiler.

For now, I will calculate density using the Wagner-Pruss volumes as you suggest, but will be suspicious of deposition estimates until I am satisfied that they are OK, or until I get a different activity model implementation.
