### ISSUE TITLE
Delete Default Class Constructors which uses ChemicalSystem

### ISSUE THREAD

**Issue by armandoeng** [reaktoro/reaktoro#45]
Classes which uses ChemicalSystem should be instantiated at least with a ChemicalSystem. So, there is no use for Class constructors with no parameters, deleting them.

At same side, an empty Chemical System can cause problems in the program (for now, it was show that cause crash on operator<< at ChemicalState. It is a good idea to delete his default constructor.

**Comment by allanleal** [comment]
From the top of my head (other classes missing for sure):

```c++
ChemicalSystem() = delete;
ChemicalState() = delete;
EquilibriumProblem() = delete;
EquilibriumSolver() = delete;
EquilibriumPath() = delete;
KineticSolver() = delete;
KineticPath() = delete;
Partition() = delete;
...
```

We'll also need to delete these constructors at the python side (`.def(init<>())`.

**Comment by allanleal** [comment]
This is now in place in Reaktoro v2.
