### ISSUE TITLE
Add automated tests run in CI

### ISSUE THREAD

**Issue by tadeu** [reaktoro/reaktoro#5]
@allan, we have have some Python tests that we'll be adding next, but we'd also like to add a step to run the current Reaktoro tests. What is your current "workflow" to run the tests locally? Do you use `ctest`?

**Comment by allanleal** [comment]
I just started yesterday introducing some tests with Catch2. All test files get compiled into an executable called ReaktoroTests. Executing this file executes all tests.

However, the compile time is increasing with this. Each test file takes some seconds to compile (10-20 s in good cases) and I'm considering doing all tests with pytest.

What about the following: running pytest in the top level directory causes all tests to be executed?

**Comment by nicoddemus** [comment]
> running pytest in the top level directory causes all tests to be executed?

Sounds good to me. We can also use [pytest-cpp](https://github.com/pytest-dev/pytest-cpp) to run any existing C++ tests along with Python tests (although only Google.Tests and Boost::Test are supported atm).

**Comment by allanleal** [comment]
Didn't know about that - thanks! But it does not solve the long compilation time issue, right? The idea would be to have all tests in python for convenience reasons and also to decrease compilation time.

**Comment by nicoddemus** [comment]
> Didn't know about that - thanks! But it does not solve the long compilation time issue, right? The idea would be to have all tests in python for convenience reasons and also to decrease compilation time.

Yes you are right. I agree with you that we probably should move all tests to Python, for the reasons you mention. 👍 😁

**Comment by tadeu** [comment]
Ok, using only {{pytest}} sounds good for now. After merging PR #4 we'll follow with adding some tests then.
