### ISSUE TITLE
Better method to search index in vectors using names

### ISSUE THREAD

**Issue by armandoeng** [reaktoro/reaktoro#53]
If you have to find and index by name on reaktoro, it make a loop and compares each name to find it. Maybe it could implement a hash table that stores the names and the index, so this search is faster, enabling the practical use of functions that receive a name as argument.

**Comment by allanleal** [comment]
Hi @armandoeng , thanks for the suggestion. Could you please post your use case? Are you talking about the member method `ChemicalSystem::indexSpecies` or other in particular?

Usually, you want to store these indices locally (say, at a configuration stage of your simulation), and then use them throughout your application, without calling these index methods again and again.

**Comment by armandoeng** [comment]
> Are you talking about the member method `ChemicalSystem::indexSpecies` or another method in particular?
Exactly. 

> Usually, you want to store these indices locally (say, at a configuration stage of your simulation), and then use them throughout your application, without calling these index methods again and again.
I'm doing that right now. But I think that could be done by ChemicalSystem instead.

**Comment by allanleal** [comment]
OK -- adding a member data `std::unordered_map<std::string, Index> indexmap` and then using `indexmap.find` method to check for existence and also getting the index?

**Comment by armandoeng** [comment]
> OK -- adding a member data `std::unordered_map<std::string, Index> indexmap` and then using `indexmap.find` method to check for existence and also getting the index?

Yes, Im doing exactly that.

**Comment by allanleal** [comment]
This has been improved in [Reaktoro v2](https://reaktoro.org) with classes [SpeciesList](https://reaktoro.org/api/classReaktoro_1_1SpeciesList.html), [ElementList](https://reaktoro.org/api/classReaktoro_1_1ElementList.html), and [PhaseList](https://reaktoro.org/api/classReaktoro_1_1PhaseList.html).

~~~py
print("Index of species H+ is ", system.species().find("H+"))
print("Index of phase Calcite is ", system.phases().find("Calcite"))
print("Index of element Si is ", system.elements().find("Si"))
~~~

Check the API reference of those classes to learn more about additional methods to obtain indices of species/elements/phases.
