### ISSUE TITLE
Add a function that accepts a string vector to chemical compounds on ChemicalEditor

### ISSUE THREAD

**Issue by armandoeng** [reaktoro/reaktoro#54]
At function addAqueousPhase compounds are passed as string and species are passed as string vector.
But, the implementation of these functions receive both string vectors (Imp struct). I think that, instead of using overload functions for different things, we could change names to do different things, and the overload option to the function to add compounds as string or string vector.

For example:
addAqueousPhaseWithCompounds(string)
addAqueousPhaseWithCompounds(vector<string>)
addAqueousPhaseWithSpecies(vector<string>)

In that way, we avoid unnecessary steps in some cases.

**Comment by allanleal** [comment]
The use of overloaded methods `addAqueousPhase` (and also `addGaseousPhase`, `addMineralPhase`) can indeed be misleading and confusing. 

~~~cpp
ChemicalEditor::editor.addAqueousPhaseWithSpecies(const StringList& names);
ChemicalEditor::editor.addAqueousPhaseWithElements(const StringList& symbols);
ChemicalEditor::editor.addAqueousPhaseWithElementsOf(const StringList& formulas);
~~~

~~~cpp
editor.addAqueousPhaseWithSpecies({"H2O(l)", "H+", "OH-"}); // or
editor.addAqueousPhaseWithSpecies("H2O(l) H+ OH-");

editor.addAqueousPhaseWithElements({"H", "O", "C"});  // or
editor.addAqueousPhaseWithElements("H O C"); 

// both cases below are equivalent to the immediate two above editor.addAqueousPhaseWithElementsOf({"H2O", "CO2"});  // or
editor.addAqueousPhaseWithElementsOf("H2O CO2"); 
~~~

The suggested names above results from current development of library `Atomik` (the library that will contain the basic constructs for Reaktoro v2.0.0, such as `Element`, `Substance`, `Reaction`, `Substances`, `Elements`).

For example:

~~~
Substances substances('somedatabase.json');

Substances aqueous = substances.withType("aqueous").withElementsOf("H2O NaCl CO2");
Substances gaseous = substances.withType("gaseous").withFormulas("H2O CO2");
~~~

**Comment by armandoeng** [comment]
Perfect for me. :)

**Comment by armandoeng** [comment]
I started the implementation of this issue. I was thinking that maybe addAqueousPhaseWithElementsOf is not necessary, as addAqueousPhaseWithElements has the same functionality. Are you thinking something specific for that?

**Comment by allanleal** [comment]
Both methods below would have the same effect:

~~~
editor.addAqueousPhaseWithElements("H O C");
editor.addAqueousPhaseWithElementsOf("H2O CO2");
~~~

In `addAqueousPhaseWithElementsOf`, a list of formulas are given, which a broken down into elements (e.g., `H2O` and `CO2`, when broken down, produce a vector of element names `{"H", "O", "C"}`).

For method `addAqueousPhaseWithElements`, on the other hand, we should only provide element symbols. The following will result in a runtime error:

~~~
editor.addAqueousPhaseWithElementsOf("H2O CO2");
~~~

remarking that `H2O` (or `CO2`) are not recognized as element names.

**Comment by armandoeng** [comment]
> 
> 
> Both methods below would have the same effect:
> 
> ```c++
> editor.addAqueousPhaseWithElements("H O C");
> editor.addAqueousPhaseWithElementsOf("H2O CO2");
> ```
> 
> In `addAqueousPhaseWithElementsOf`, a list of formulas are given, which a broken down into elements (e.g., `H2O` and `CO2`, when broken down, produce a vector of element names `{"H", "O", "C"}`).
> 
> For method `addAqueousPhaseWithElements`, on the other hand, we should only provide element symbols. The following will result in a runtime error:
> 
> ```c++
> editor.addAqueousPhaseWithElementsOf("H2O CO2");
> ```
> 
> remarking that `H2O` (or `CO2`) are not recognized as element names.

I think you mean that:
```c++
editor.addAqueousPhaseWithElements("H2O CO2");
```
would return an error, rigth, and 
```c++
editor.addAqueousPhaseWithElementsOf("H2O CO2");
```
would be accepted.

**Comment by allanleal** [comment]
Yes exactly, silly copy and paste error - I'll edit my previous comment.

**Comment by armandoeng** [comment]
Implemented on https://github.com/reaktoro/reaktoro/pull/61
