### ISSUE TITLE
Properties shown with ChemicalState output

### ISSUE THREAD

**Issue by martinvoigt** [reaktoro/reaktoro#58]
I think it would be nice to group the species in the standard ChemicalState output by element, and then sort them by abundance (similar to PHREEQC output) - this would make it a lot easier to quickly scan the output.

Also, for me the molalities (mol / kg water) would be a more interesting property to display instead of the mole fractions.

Maybe the properties that are shown by default could be added as some sort of configuration option?

**Comment by allanleal** [comment]
Instead of mole fractions, we could have concentrations: this then defaults to mole fraction for solvent (H2O), molalities for aqueous solutes, and mole fractions for gases (and minerals in solid solutions).

> Maybe the properties that are shown by default could be added as some sort of configuration option?
I'm thinking in implementing different functions (or a single function that accepts options, possibly a more preferred idea)  to print state. This would then allow one to specify what should be printed.

**Comment by martinvoigt** [comment]
For me as an aqueous geochemist the properties I usually look at first are these ones (in descending order of interest):

1. pH, sometimes also alkalinity
2. Concentrations of elements and species of interest in the aqueous solution
3. Saturation states of solids/gases of interest (with respect to the aqueous solution)
4. How much of a phase reacted, in case this was part of the model
5. Temperature, pressure, ionic strength, charge balance, masses of phases, etc. - mainly to verify the model ran correctly, if something seems off

I think the idea of having different functions to display these various things would be great, but it's a tough thing to say what should be included in the "default" output - the things I listed above are what I personally look at most, but this might be different for others.

Also, it might be useful to have some sort of filter or cut-off as an option for the lists/tables: For example, show only the most abundant species that make at least 99% of the total abundance of each element - often there are lots of species with very minor abundance, that are not of much interest most of the time. Same for displaying saturation states - a filter to only show phases that are close to equilibrium with respect to the aqueous solution would be great.

**Comment by allanleal** [comment]
Hi Martin, as mentioned in this other issue #57 that I just closed, this has been improved in [Reaktoro v2](https://reaktoro.org). Please check these examples:

* [Computing chemical properties](https://reaktoro.org/tutorials/basics/computing-chemical-properties.html)
* [Computing aqueous properties](https://reaktoro.org/tutorials/basics/computing-aqueous-properties.html)

Here is an example of the printed table for an object of class [**AqueousProps**](https://reaktoro.org/api/classReaktoro_1_1AqueousProps.html) that shows species and element molalities, pH, pE, Eh, saturation indices of minerals, gases. More will come soon!

![image](https://user-images.githubusercontent.com/5825588/152538805-0f90a314-41f9-4a9b-9120-9375600b6c50.png)

Please get in tough if you have further suggestions! Thanks for the discussion and feedback.
