### ISSUE TITLE
Implement class GeochemicalState

### ISSUE THREAD

**Issue by allanleal** [reaktoro/reaktoro#59]
Currently, we have class `ChemicalState`, which stores temperature, pressure, and amounts of species distributed among one or more phases. This class should be general (i.e., applicable to any chemical system). However, it currently has some hard coded geochemical concepts in it (e.g., when printing a `ChemicalState` object, there is a section for aqueous phase, showing pH, pe, ionic strength, etc). This should be stripped from `ChemicalState`, otherwise those interested in chemical systems without water/aqueous phase will experience runtime errors when printing a `ChemicalState` object.

If the application of interest is related to geochemical modeling, then one has to convert a `ChemicalState` object into a `GeochemicalState` one:

~~~python
state = equilibrate(problem)  # type(state) is ChemicalState
state = GeochemicalState(state)  # type(state) is now GeochemicalState

state.output()  # this will now output in a format that (most) geochemists are happy with
~~~

To address issue #57, we should also have a member method that converts the state into a dictionary so that it can be nicely printed in a Jupyter notebook using `pandas`.

Foreseen steps to accomplish this task:

- [ ] implement GeochemicalState class
- [ ] implement a conversion method from a GeochemicalState object to a dictionary
- [ ] implement methods `pH`, `pe`, `Eh`, `ionicStrength`, `alkalinity`, `saturationIndex`, etc.
- [ ] species should be printed in sections of chemical elements
- [ ] species with higher amounts should be higher in the column
- [ ] species with relatively low amounts should be filtered out from the output
- [ ] phases that are not close to saturation with respect to the aqueous phase should be left out (possibly displayed in another section for completeness)

Printing could follow the following suggestion of @martinvoigt (#58):

> pH, sometimes also alkalinity
Concentrations of elements and species of interest in the aqueous solution
Saturation states of solids/gases of interest (with respect to the aqueous solution)
How much of a phase reacted, in case this was part of the model
Temperature, pressure, ionic strength, charge balance, masses of phases, etc. - mainly to verify the model ran correctly, if something seems off

**Comment by martinvoigt** [comment]
Having the default `ChemicalState` output not printing info about fluids seems sensible... but `GeochemicalState` could be a bit misleading as a name - there's plenty geochemical systems without any aqueous solutions - maybe something like `AqueousSolutionState` or something like that?

In general, maybe some functions to quickly output information/compositions of the different phases present in a `ChemicalState` would be nice (maybe they're already there and I just didn't see them yet) - something like this:
```
state.AqueousSolutionState()
state.GasPhaseState()
state.MineralComposition(id/name/...)
```

**Comment by allanleal** [comment]
>  but GeochemicalState could be a bit misleading as a name - there's plenty geochemical systems without any aqueous solutions

You're right. What about `AquaticState` instead? This term seems much more specific to systems that have an aqueous phase than `GeochemicalState`. 

`AqueousSolutionState` could also be misleading in which one thinks it comprises of only an aqueous phase, while there could be a gas phase and precipitated minerals.

> In general, maybe some functions to quickly output information/compositions of the different phases present in a ChemicalState would be nice (maybe they're already there and I just didn't see them yet) - something like this:
state.AqueousSolutionState()
state.GasPhaseState()
state.MineralComposition(id/name/...)

If we do this, then `ChemicalState` class is no longer generic, and it assumes aqueous, gaseous, and mineral phases are there in the system. This is something that `ChemicalEditor` should also not have in the future (those `addAqueousPhase`, `addGaseousPhase`, and `addMineralPhase`). Instead, we should have a similar class for, say, aquatic systems, cement systems, etc.

**Comment by tadeu** [comment]
> If we do this, then `ChemicalState` class is no longer generic, and it assumes aqueous, gaseous, and mineral phases are there in the system.

Could it still be generic while having some "specific" methods for specific cases? For example, `ChemicalState::getAqueousSolutionState()` could return an `std::optional<AqueousSolutionState>` (or a nullable `std::shared_ptr`), which would only hold a value in case a water phase is present. It has the drawback of needing extra `if`'s whenever an user of the library wants to use these methods, but it seems simpler than having to deal with casts and conversions for an extra type.

**Comment by allanleal** [comment]
> Prefer non-member non-friend functions to member functions, *Effective C++ Item 23*  

:)

We could then envision a free method `aqueousSolutionState(const ChemicalState&)` if we follow this advice from Scott Meyers. This would be preferable because we then don't force the implementation of `ChemicalState` (which is supposed to be applicable to any type of chemical system) to know about specifics of the system. Even if `optional` is used, there will still be code in that class that only makes sense for systems with aqueous phases.

But then, this alternative (free method) would not be much different (syntax-wise) from having a dedicated class that extends `ChemicalState` with methods for retrieving properties of aqueous solution states. The return of that method would need to be an object of some class anyway.

I'm just not sure what is the best name for this class. `AqueousState`, `AquaticState`, a longer name such as `AqueousSolutionState`? I'm more inclines towards the first two (I think I have implemented a class `AqueousState` at some point -- need to check if it is still there in the code (or if I'm mistaken!).

**Comment by tadeu** [comment]
I'm all in favor of free functions also :)

I was assuming that it needed internal details from `ChemicalState`, so that it wouldn't be able to be non-friend (or non-member). But if this is not the case, then I think it's ok.

Just one thing about "a dedicated class that _extends_ `ChemicalState`": "extends" here is meaning "inherits"? At first I understood this (inheritance), this is why I thought that dealing with new extension types would be more complicated... but if it just "extends" by wrapping some results and performing some extra calculations, then it really seems ok.

**Comment by allanleal** [comment]
We could extend with inheritance or with composition. I guess when you say wrapping this also means composition, right? I think this should be simpler. This class, say `AqueousState`, should only be used quickly, to get for info about the state of the aqueous phase. We should promote the use of `ChemicalState` instead of algorithms (say, reactive transport modeling).

Possible constructors

~~~c++
AqueousState(const ChemicalSystem& system);
AqueousState(const ChemicalState& state);
~~~

One could then use this class even without using a `ChemicalState` object:

~~~python
state = AqueousState(system)
state.setTemperature(50, "celsius")
state.setMolalities(values)

print( state.pH() )
print( state.saturationIndex("Calcite") )
~~~

I see there will be some repeated methods from `ChemicalState` (e.g., `setTemperature`, `setPressure`).

**Comment by tadeu** [comment]
Hmm, I was thinking it would be only for outputting, but it could also be used for input (`setMolalities`). Well, it also would make sense to use inheritance... `AqueousState` could inherit from `ChemicalState`, and, for example, `equilibrate` could even choose to return one type or another, depending if there's a water phase at equilibrium.

At first I just thought it would be more complicated, but it looks nice.

**Comment by allanleal** [comment]
> At first I just thought it would be more complicated, but it looks nice.

Let's experiment inheritance and see how it goes. 

What we can essentially foresee for future development is like additional classes for specific chemical contexts. We could also have, say, an `AqueousSystem` or `AquaticSystem` class that has convenient mechanisms for its construction:

~~~python
system = AqueousSystem("Na Cl C Ca Mg Fe")

speciation = AqueousSpeciation(system)  # for definition of an aqueous speciation problem
speciation.setTemperature(40, "celsius")
speciation.sarturatedWith("Calcite")

state = equilibrate(speciation)  # state is of type AqueousState 

print(state.html())  # I wonder if Jupyter notevook will pretty print html?!
~~~

@martinvoigt You might know if Jupyter notbook will handle the above code as you wish (state output as html).

**Comment by martinvoigt** [comment]
> @martinvoigt You might know if Jupyter notbook will handle the above code as you wish (state output as html).

Something like this works:
```
from IPython.core.display import display, HTML
display(HTML(state.html()))
```
Of course it would be nice if this would be automatic, so one could just use `state()` and it automatically prints it in a suitable format, same as `pandas` is doing it (not sure how they do it though).

Just to clarify: You want a `ChemicalState` class for systems with just solids, and then `AqueousState` for systems with solids + an aqueous solution? What about gases? What if it becomes more complicated, i.e. two fluids are formed (e.g. high NaCl fluid, and low NaCl fluid) that cannot easily be classified as a liquid or a gas - how is stuff like that handled right now, or how (if so) do you plan to implement that? Even more general: is there any plan to support melt formation, or are you not going there for now?
Depending on what you want to support now, or in the future, it might be helpful to already think about this now...

Also, what do you mean by
> We should promote the use of ChemicalState instead for algorithms (say, reactive transport modeling).

Isn't an aqueous phase involved in pretty much all reactive transport modelling?

**Comment by allanleal** [comment]
Hi @martinvoigt 

> Just to clarify: You want a ChemicalState class for systems with just solids

A `ChemicalSystem` class represents multiphase systems in general - any combination of phases, of any type, as many types as you need, as many repeated types you want. A `ChemicalState` object represents the compositional state of that generic multiphase system.

What we envision here is an `AqueousState` class to represent the state of an aqueous fluid (if you have more than one aqueous fluid in the system, then you create one `AqueousState` object for each of them, using their names). 

By doing this, we avoid "poluting" the ChemicalState class with concepts that are not always applicable (for example, a method pH should not be defined in ChemicalState, but in AqueousState).

> Even more general: is there any plan to support melt formation, or are you not going there for now?

The infrastructure of the code permits any type of phase to be added. But there is no thermodynamic model for melts yet. Basically, we need to construct a `Phase` object that has:

1) the melt components (their names, formulas)
2) a function that computes their standard thermodynamic properties for a given T and P
3) a function that computes their excess properties for given T, P, n (e.g., activity coefficients)

> Isn't an aqueous phase involved in pretty much all reactive transport modelling?

For reactive transport, we need a `ChemicalState` object for each mesh cell/node (or DOF, degree of freedom, in finite element methods). The `AqueousState` class will have some memory and computing overhead, and we should promote perhaps only one instance for the whole simulation (or one per process/thread if in parallel). One can then loop through the nodes and update this AqueousState object, and get, say, pH. But I could be wrong here, and perhaps an AqueousState would be more adequate. I'll see if I start this project next week.

> Of course it would be nice if this would be automatic, so one could just use state() and it automatically prints it in a suitable format, same as pandas is doing it (not sure how they do it though).

Agree. We want something dead simple:

~~~python
state = equilibrate(problem)

state

<< nice display of the state here >>
~~~

**Comment by martinvoigt** [comment]
Many thanks - this makes sense. I was mixing up `ChemicalSystem` and `ChemicalState`...

> For reactive transport, we need a ChemicalState object for each mesh cell/node (or DOF, degree of freedom, in finite element methods). The AqueousState class will have some memory and computing overhead, and we should promote perhaps only one instance for the whole simulation (or one per process/thread if in parallel). One can then loop through the nodes and update this AqueousState object, and get, say, pH. But I could be wrong here, and perhaps an AqueousState would be more adequate. I'll see if I start this project next week.

How would you implement mixing/diffusion/dispersion etc in a reactive transport model with only one fluid composition at a time? Maybe I'm missing something?

**Comment by allanleal** [comment]
> How would you implement mixing/diffusion/dispersion etc in a reactive transport model with only one fluid composition at a time? Maybe I'm missing something?

That's why a `ChemicalState` object for each cell is needed, instead of `AqueousState`, since the former has the composition of all phases (fluid and solid phases). If `AqueousState` is implemented as inherited from `ChemicalState`, then it does not matter, as an object of `AqueousState` will also have the same information as `ChemicalState` plus additional properties associated with the aqueous fluid (e.g., pH, pe, etc.). If most aqueous properties are not needed during the simulation, there will be more memory used without real need. That's why I talk about a loop to extract only the properties of interest (e.g., extract only pH throughout the nodes/cells, **but not their** pe, Eh, alkalinity, ionic strength, molalities, etc.).

**Comment by martinvoigt** [comment]
Ok - was mixing up things again. So `ChemicalState` is meant to be collection of multiple phases, but `AqueousState` just of one aqueous phase? If that's the case, I would suggest not naming the latter something like `AqueousPhase` - both classes ending with `State`, but one of them being a collection of multiple phases, and the other just one phase is quite confusing!

**Comment by allanleal** [comment]
> So ChemicalState is meant to be collection of multiple phases

Yes, a collection of chemical state (composition, temperature, pressure) of multiple phases.

> AqueousState just of one aqueous phase? 

If `AqueousState` is implemented as inherited from `ChemicalState`, then it also has info about all other phases. Maybe not needed or adequate.

> I would suggest not naming the latter something like AqueousPhase - both classes ending with State, but one of them being a collection of multiple phases, and the other just one phase is quite confusing!

Great - thanks for letting me know this is confusing. `AqueousPhase` is already used - a class for defining an aqueous phase, its species, its activity model, etc.

Maybe `AqueousProperties` or `AqueousProps`?

~~~python
state = equilibrate(problem)

props = AqueousProps(state)

print( props.pH() )
print( props.pe() )
print( props.alkalinity() )

print( props )  # the whole thing is a nice formatted (pandas supported) table.
~~~

**Comment by martinvoigt** [comment]
But which aqueous phase (if there is more than one) would be printed, in this case? All of them? etc?
Is (or would it be) possible to have something like that:

```
state = equilibrate(problem)
phase1 = state.phases[1] # and/or state.phase('solid/aqueous/gas/name/...')
phase1.composition() # some general functions for all phases, no matter if solid, aqueous, etc
phase1.ph() # calculates pH on the fly if aqueous phase, or returns null/error/whatever if it's not applicable
```

in this specific case there would also be some functions that are not applicable for every type of phase, but would a function definition itself occupy a lot (or any) memory, if the property (pH etc) is only calculated on the fly if the function is called?

**Comment by allanleal** [comment]
By default, `"Aqueous"` is the name of the aqueous phase. If there are more aqueous phases:

~~~python
props1 = AqueousProps(state, "Aqueous1")
props2 = AqueousProps(state, "Aqueous2")
~~~

Commenting on your suggestion. In Reaktoro, state is decoupled from system/phase definitions. For example, `ChemicalSystem` has no compositional information - only information about the phases, their species, and the elements that constitute them. The same for the classes `Phase`, `Species`, `Element`, `Reaction`, etc. - they store no compositional data. This permits a single instance of these classes to be used for many different chemical states. So, for example, in a simulation, say, reactive transport, where 1'000'000 states are needed, one `ChemicalSystem` object can be shared among all such states.


> phase1.ph() # calculates pH on the fly if aqueous phase, or returns null/error/whatever if it's not applicable

This usage is convenient, but not necessarily appropriate from software development point of view. If this approach is used, then nothing prevents dozens of more methods for all possible properties that only make sense in specific cases.

**Comment by martinvoigt** [comment]
> This usage is convenient, but not necessarily appropriate from software development point of view. If this approach is used, then nothing prevents dozens of more methods for all possible properties that only make sense in specific cases.

ok, fair enough :)

In case you didn't see it yet, this is how you can create custom IPython/Jupyter output formats for your objects: [https://ipython.readthedocs.io/en/stable/config/integrating.html](https://ipython.readthedocs.io/en/stable/config/integrating.html)

**Comment by allanleal** [comment]
> In case you didn't see it yet, this is how you can create custom IPython/Jupyter output formats for your objects: https://ipython.readthedocs.io/en/stable/config/integrating.html

Cool - we can then define a method `_repr_html_` for the Python interface of Reaktoro classes, and they will be formatted nicely (using HTML) automatically by Jupyter.

**Comment by onoedland** [comment]
Have there been any updates on this since last year? I have just started experimenting with using Reaktoro in Python, but I need to be able to extract, e.g., pH during a reactive transport simulation run . What is the simplest way to do that now, other than having to go via generated output text files (which is very cumbersome)?

**Comment by tadeu** [comment]
We are using [Reaktoro::ChemicalProperty::pH](https://reaktoro.org/cpp/namespaceReaktoro_1_1ChemicalProperty.html#ab26aff51ad8a6cde3dade6674fc098de) in order to extract pH in C++, e.g.:

```cpp
auto pH = Reaktoro::ChemicalProperty::pH(chemical_system)(chemical_properties).val;
```

**Comment by onoedland** [comment]
Yes, noticed that also, but it does not seem like it is possible to call it from Python?

**Comment by allanleal** [comment]
Here is a complete demo on how to create a pH function and evaluate it in Python:

~~~py
from reaktoro import *

db = Database("supcrt98.xml")

editor = ChemicalEditor(db)

editor.addAqueousPhaseWithElements("H O Na Cl C Ca Mg Si")
editor.addGaseousPhase("H2O(g) CO2(g)")
editor.addMineralPhase("Halite")
editor.addMineralPhase("Calcite")
editor.addMineralPhase("Magnesite")
editor.addMineralPhase("Dolomite")
editor.addMineralPhase("Quartz")

system = ChemicalSystem(editor)

problem = EquilibriumProblem(system)

problem.setTemperature(70, "celsius")
problem.setPressure(100, "bar")
problem.add("H2O", 1.0, "kg")
problem.add("CO2", 2.0, "mol")
problem.add("NaCl", 1.0, "mol")
problem.add("CaCO3", 10.0, "g")
problem.add("MgCO3", 5.0, "g")
problem.add("Quartz", 1.0, "mol")

state = equilibrate(problem)

properties = state.properties()

pHfunc = ChemicalProperty.pH(system)

pH = pHfunc(properties)

print(f"The pH of the aqueous phase is {pH.val}.")
print(f"Its sensitivity with respect to speciation is:")
print("Species names : ∂(pH)/∂n (in 1/mol)")
for i, species in enumerate(system.species()):
    print(f"{species.name():>13} : {pH.ddn[i]}")
~~~

**Comment by allanleal** [comment]
Get in touch with us via Gitter for a more prompt response: https://gitter.im/reaktoro/community

**Comment by onoedland** [comment]
Thank you, I will ask there if I have any more questions!
