### ISSUE TITLE
reaktoro activated, but still show "ModuleNotFoundError: No module named 'reaktoro' "     

### ISSUE THREAD

**Issue by lachlan11** [reaktoro/reaktoro#67]
Hi,
after running "Conda env list", Ｉcan clearly see Reaktoro is installed.

C:\Users\Yue Liu>conda env list
# conda environments:
#
base                  *  C:\Miniconda
reaktoro                 C:\Miniconda\envs\reaktoro

I can activate it as well bu typing "conda activate reaktoro", 

However, I cannot print the path, it shows error exactly like what we see on reaktoro.org.

Traceback (most recent call last):
    File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'reaktoro'

I tried to open the reaktoro environment using pycharm, and running the example of solubility of CO2, it tells that no module named reaktoro as well.   and the second error "database is not defined"

Does anyone can tell me what should do?  I really appreciate your help.

**Comment by nicoddemus** [comment]
Hi @lachlan11,

At first glance your steps seem correct. Can you please post the full output of this sequence of commands?

```
$ conda info
$ conda devenv
$ conda activate reaktoro
```

**Comment by allanleal** [comment]
@lachlan11 I assume you built Reaktoro, right? If so, you might need to do a `make install` or `cmake --build <builddir> --taget install` to install the library and header files to your conda environment. 

Most likely the predefined `PYTHONPATH` for Windows is not correct (those lines below in the file `environment.devenv.yml`):

~~~yaml
    - {{ root }}\artifacts\python\Lib\site-packages                              # [win]
    - {{ root }}\build\lib\python{{ python_version }}\site-packages              # [win]
    - {{ root }}\build\lib64\python{{ python_version }}\site-packages            # [win]
~~~

Maybe you want to consider `conda install reaktoro` instead, which will require no build.

**Comment by lachlan11** [comment]
> $ conda info
> $ conda devenv
> $ conda activate reaktoro

Hi @nicoddemus,

Thanks for your help. please see attached results by running your suggested code.

C:\Users\Yue Liu>conda info

     active environment : None
       user config file : C:\Users\Yue Liu\.condarc
 populated config files : C:\Users\Yue Liu\.condarc
          conda version : 4.6.8
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\Miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/label/gcc7/win-64
                          https://conda.anaconda.org/conda-forge/label/gcc7/noarch
          package cache : C:\Miniconda\pkgs
                          C:\Users\Yue Liu\.conda\pkgs
                          C:\Users\Yue Liu\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda\envs
                          C:\Users\Yue Liu\.conda\envs
                          C:\Users\Yue Liu\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


C:\Users\Yue Liu>conda devenv
File "C:\Users\Yue Liu\environment.devenv.yml" does not exist.

C:\Users\Yue Liu>conda activate reaktoro

(reaktoro) C:\Users\Yue Liu>

![reaktoro error](https://user-images.githubusercontent.com/48546975/54502484-fd8b9100-497e-11e9-916f-9a4393da8887.png)

**Comment by lachlan11** [comment]
> 
> 
> @lachlan11 I assume you built Reaktoro, right? If so, you might need to do a `make install` or `cmake --build <builddir> --taget install` to install the library and header files to your conda environment.
> 
> Most likely the predefined `PYTHONPATH` for Windows is not correct (those lines below in the file `environment.devenv.yml`):
> 
> ```yaml
>     - {{ root }}\artifacts\python\Lib\site-packages                              # [win]
>     - {{ root }}\build\lib\python{{ python_version }}\site-packages              # [win]
>     - {{ root }}\build\lib64\python{{ python_version }}\site-packages            # [win]
> ```
> 
> Maybe you want to consider `conda install reaktoro` instead, which will require no build.

hi allenleal,

You are right. That is where the problem is. I agree.

I did tried using conda to install reaktoro, but failed I guess. tried many times actually.

Can you please tell me more how to change the path by using cmake? 

See some results below.
![reaktoro cmake](https://user-images.githubusercontent.com/48546975/54503153-0af64a80-4982-11e9-841e-109134f7da4b.jpg)

**Comment by lachlan11** [comment]
> 
> 
> Hi @lachlan11,
> 
> At first glance your steps seem correct. Can you please post the full output of this sequence of commands?
> 
> ```
> $ conda info
> $ conda devenv
> $ conda activate reaktoro
> ```

hi @nicoddemus

Thanks for your help.

See results below. Hope this will help you and me figure out what is the matter.

![reaktoro errot](https://user-images.githubusercontent.com/48546975/54506257-ce315000-498f-11e9-9814-c46d4ae9367d.jpg)

**Comment by allanleal** [comment]
> I did tried using conda to install reaktoro, but failed I guess. tried many times actually.

May I kindly ask you to try again and report, in a new issue, the failure you observed using `conda install reaktoro`? 

I would only recommend the CMake-based installation alternative for users with a basic understanding of building codes. For example, developers.

If you want to try, do:

~~~
cd reaktoro
conda devenv
conda activate reaktoro
cmake -DPREFIX=%CONDA_PREFIX% -P install 
~~~

I believe you are using Windows. If Unix based system:

~~~
cmake -DPREFIX=$CONDA_PREFIX -P install
~~~
