### ISSUE TITLE
installing reaktoro

### ISSUE THREAD

**Issue by lachlan11** [reaktoro/reaktoro#70]
Hi @allanleal

Follow your request, This is a new issue following previous installing issues.

I uninstalled conda, reaktoro, cmke, etc, and restarted my desktop (win).

Starting from 

1. conda config --append channels conda-forge
2. conda install reaktoro
3. conda install -n base conda-devenv
4. download reaktoro from github
5. conda devenv (In the root of the reaktoro directory, execute:)

But, I have encountered a new problem. Please help me check what is the matter.  thanks very much.

[error.txt](https://github.com/reaktoro/reaktoro/files/2980843/error.txt)

**Comment by allanleal** [comment]
@lachlan11 Thanks for reporting this.

@nicoddemus The attached error has to do with recent update of conda-devenv. How do we ensure that conda installs the most up to date version of conda-devenv?

@lachlan11 Back to you. If you use `conda install reaktoro`, you can forget about conda-devenv (which is for those developing Reaktoro and/or building from source). 

You only need the following commands:

~~~
conda config --append channels conda-forge
conda install reaktoro
~~~

or just:

~~~
conda install conda-forge::reaktoro
~~~

which means install reaktoro from the conda-forge channel.

Could you please check that `python -c 'import reaktoro'` runs without any error output?

If it does, please post the output of:

**Wndows**
~~~
echo %PYTHONPATH%
~~~

**Linux and macOS**
~~~
echo $PYTHONPATH
~~~

**Comment by lachlan11** [comment]
> 
> 
> @lachlan11 Thanks for reporting this. You most likely need to update conda-devenv:
> 
> ```
> conda update conda-devenv
> ```
> 
> However, if you use `conda install reaktoro`, you can forget about conda-devenv (which is a tool for those developing Reaktoro and/or building from source).
> 
> You only need the following commands:
> 
> ```
> conda config --append channels conda-forge
> conda install reaktoro
> ```
> 
> or just:
> 
> ```
> conda install conda-forge::reaktoro
> ```
> 
> which means install reaktoro from the conda-forge channel.
> 
> Could you please check that `python -c 'import reaktoro'` runs without any error output?
> 
> If it does, please post the output of:
> 
> **Wndows**
> 
> ```
> echo %PYTHONPATH%
> ```
> 
> **Linux and macOS**
> 
> ```
> echo $PYTHONPATH
> ```
> 
> @nicoddemus The attached error has to do with recent update of conda-devenv. How do we ensure that conda installs the most up to date version of conda-devenv?

Hi allanleal,

I tried your idea, but it doesn't work. 

Actually, I tried it many times before I post the first issue, they all does not work.

Anyway, thanks very much. I guess I have to give up on it. just take too much time 
[error2.txt](https://github.com/reaktoro/reaktoro/files/2986120/error2.txt)

**Comment by allanleal** [comment]
OK, thanks for trying. It looks to me the package has been installed successfully, but you are having difficulties with python. Should you need further help in the future, let us know!

**Comment by allanleal** [comment]
For future reference, for those building Reaktoro from source, there seems to be a need to do `conda update conda-devenv` in addition to `conda install conda-devenv` at the moment.

**Comment by tadeu** [comment]
`conda install conda-devenv` should already install the latest version, do you know what happened exactly, is this reproducible?
