### ISSUE TITLE
reaktoro in MacOSX

### ISSUE THREAD

**Issue by redoxmatlab** [reaktoro/reaktoro#87]
I've tries everything but reaktoro does not work at all in Macos. help please?

**Comment by allanleal** [comment]
Hi @redoxmatlab ! We have made it possible to install reaktoro with conda in both Linux and Windows, using `conda install reaktoro`. 

Recently, @alexandrebbruno resolved some issues related to macOS, which makes us close to have reaktoro available for macOS too using conda.

How did you try installing it? By building from sources?

**Comment by allanleal** [comment]
As of early today, we can now install Reaktoro in macOS using conda install reaktoro (or conda install conda-forge::reaktoro if the conda-forge channel has not yet been appended to the list of channels that conda uses to search for packages). Before, this conda installation support only existed for Windows and Linux.
